### ISSUE TITLE
Restructure translation keys

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#105]
All translation keys should be namespaced with RQG (with the exception of ITEM that is a foundry namespace).

Below RQG namespace the structure should be `<sheet/page/dialog>.<group-specificdialog>.key`

For example `RQG.ActorSheet.CombatTab.someKey` if the sheet/dialog is simple it's fine to skip the second grouping for example
`RQG.PassionSheet.someKey`

There are also exception for groupings that can be deeper, like `RQQ.ActorSheet.TopArea.Characteristic.strength` and for translations that appear in multiple places we can have `RQG.Common.CultRank.initiate`

**Comment by Moonpile** [comment]
- Item (Foundry's default place to look for the localizable names of items)
- RQG
-- Settings
-- characteristic (merge with characteristicfull) ie:
---"str": "STR"
---"strength": "Strength"
-- ResultEnum

**Comment by wake42** [comment]
A few thoughts... Right now we only have one actor "character" but we have talked about adding some sort of look actor etc. It will make the content keys longer, but should we have RQG.Actor.Character.xxx to future proof it?

Homeland and Occupation should probably be under background.

RQG.Game.CombatManeuver could be a problem since you can add whatever in that field (even if you get a bunch of suggested values). It might need some thinking of how to solve that.

Other than that it look good I think.

**Comment by Moonpile** [comment]
I think if we have a loot actor, its localizations might go under "RQG.Actor.Loot.foo", or even just "RQG.LootActor.foo".

Agreed about Homeland and Occupation.

**Comment by wake42** [comment]
I agree on the RQG.LootActor idea - no need to make the structure deeper than necessary.
And for the combat manoeuvres - possibly they too should become a settings panel where you could localise the preconfigured names. I think you could switch out the values of the settings if you switch language then (hopefully).
defaultDamageType (slash, impale, bash, ...) is localisable though since it's a defined set of values.

**Comment by Moonpile** [comment]
I think ideas like the damage type will occur to us while we're doing this.  Do you think we're ready to start on this one?

**Comment by wake42** [comment]
Yes, this is a case that it good to do sooner rather than later to minimise rewrites of coming translation keys.
