### ISSUE TITLE
Show / Edit physical item description

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#117]
On physical items (gear, armor, weapons) there is a description field on the item but that is currently not visible to the players. Find a good way to visualise that. 

Also it would be good for players to be able to take notes directly on those physical items. Should we use the same description field and make that editable by the players?

**Comment by Moonpile** [comment]
Maybe make the edit Item Sheet visible to the player but just hide or disable any fields they shouldn't edit.   I think they should be able to edit the description though.

**Comment by wake42** [comment]
Is duplicated by #248
