### ISSUE TITLE
Refactor skillData learned chance

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#118]
At the moment the final chance of a skill is learnedChance + skillCategoryMod and there are checks among other things verify that you only get a chance if the learned chance > base chance in case the base chance is 0.

It would be more intuitive to have the final chance = base chance + learnedChance + skillCategoryMod. This would also simplify some checks like where we check that learnedChance isn't below baseChance. That check also had a bug if you put an active effect on a characteristic that would raise the baseChance, then the learnedChance would also be raised, but not lowered after the active effect was gone.

To do this one would need to do a migration of all skillItems where the current learnedChance is reduced by the baseChance.

**Comment by Moonpile** [comment]
Issue #101 may require this rework to have something more like "finalChance = (speciesBase + homelandBase + occupationBase + cultBase) + learnedChance + skillCategoryMod".

**Comment by wake42** [comment]
I thought about that, but came to the conclusion that it's only during character creation that is important. When the actor is created it will be more confusing to have multiple base chances I think. An alternative solution to keep track of separate chance modifications could be to add flags to the affected items, and add those bonuses directly to `gainedChance` (not `baseChance`, that I think would be more like `speciesBase`). A suggestion for flag structure on the skill items could be:
```ts
const flags =  {
  rqg: {
    creationBonuses: {
      homeland: 20
      occupation: 25
      cult: 30
    }
  }
}
```
