### ISSUE TITLE
"Yey, you got an experience check on" notification even if you already have a check

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#125]
If you have a check already, no point in this notification.

**Comment by wake42** [comment]
I've seen that. I think it's only if you do the roll from same chat card again (and you did not have exp to begin with)? 
The chat card data would need to get updated if the data from the actor/token is updated.

**Comment by wake42** [comment]
#273 fixed this error by only storing a id to the actor (thereby rereading the data when needed)
