### ISSUE TITLE
Remove linked RuneMagic when a Cult is deleted

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#128]
When a character leaves a cult it should retain the cult and all it's linked RuneMagic. Leaving a cult just means you can't replenish your Rune Points.

Deleting a Cult from an Actor on the other hand is more configuration and the RuneMagic that is linked to the Cult should also be removed then.

**Comment by Moonpile** [comment]
See RQG p282.

So if an adventurer leaves the cult they just can't replenish Rune points (and might get attacked by Spirits of Reprisal).  I guess deleting the cult is only something a player would do when the adventurer has used up all the Rune Points?

**Comment by wake42** [comment]
For an active adventurer I wouldn't delete the cult at all. But if you delete a cult then you get RuneMagic items that are not linked to and cult. There is some clumsy handling of that, but I think just deleting them would be smoother. This is a bit of an edgecase but while configuring an adventurer you might want to delete cults if you dragged in the wrong one for example.
