### ISSUE TITLE
Handle pluralized inventory items

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#132]
Come up with a strategy for handling inventory items that usually have a quantity of more than one, like arrows, or food rations.

Should we have a separate field on the inventory item for "pluralName"?

Should normally singular items, like a sword or a shield, have editable quantities?

Can we get away with just making the official object name singular for normally singular items like "Sword" and "Hauberk" and making the official object name plural for normally plural items like "Arrows" and "Rations"?

### Related
- [ ] #211

**Comment by wake42** [comment]
Having multiple names for things is probably to overcomplicate things. I think the suggestion to name things you normally have one of (like weapons or specific items) in singular, and things you normally have many of (like lunars or food rations) in plural is the best way to do it.

Closing this case
