### ISSUE TITLE
Add common rune magic when embedding a cult

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#153]
When adding a cult to an actor all the runemagic that is common to that cult should also be added.

I see two ways of doing this (and I'm leaning towards option 2)

### 1. Refactor the cult/runeMagic connection 
so that cult has a list of runeMagic items (now the link is on the runeMagic item, pointing to what cult it belongs to). The list would need to contain an object like
```js
{
  originId: string, // the uuid of a runeMagic, for example pointing to a runeMagic compendium
  embeddedId: string // the id of the runeMagic after it is embedded in the actor (empty for world items)
}
```
One downside of this refactoring is that if you have a runeMagic item and want to roll on that, you need to go through all items in the actor to find the corresponding cult since the link is the other way around.

### 2. Add a list of runemagic ~~uuid~~ rqid to cult
but keep the runeMagic items pointing to cults. The advantage of this is that the refactoring is much smaller. 
One should be able to drag multiple runeMagic items to a cult and also have a way of editing/removing from that list.

See also #236

**Comment by Moonpile** [comment]
Remember that some cults don't have all the common rune magic.  For the list see RQG starting at page 289.

**Comment by wake42** [comment]
Yes, that's why we can't use a default list, but have to embed the runeMagic list on each cult.

**Comment by Moonpile** [comment]
There should be some way of collapsing or filtering out the common rune magic so that it's easy to see the special rune magic.

**Comment by wake42** [comment]
Maybe marking the "common" spells in the rune magic table is enough? You can always rearrange your spells in the order you like them.

**Comment by Moonpile** [comment]
> Maybe marking the "common" spells in the rune magic table is enough? You can always rearrange your spells in the order you like them.

I ended up moving the special rune magic to the top for my pre-gens, but this is one where multiple people said they'd like to be able to focus on just the special Rune Magic.  Really with one or two exceptions in the common stuff, you won't care about the common stuff much of the time.
