### ISSUE TITLE
Improve UX of embedding missile weapon & projectiles

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#154]
### Problem
As it is now when embedding a missile weapon the GM needs to manually open it and connect the wanted arrow items to be able to use the missile weapon. If this could be automated / refactored the UX would be much better.

### Suggestions for solving:
When embedding a missile weapon item then show a dialog to connect an available (embedded) projectile. In most cases I think an actor will only have one kind of projectiles, but show a dialog asking which projectile to connect and with an option to not connect any. The reason to not connect could be that one has a javelin (that is a projectile for atlatl) and a self bow. You cannot shoot javelins with a self bow so it should not auto connect them. The same search would have to be done when projectile items are embedded, but this time searching for missile weapons that don't have any specified projectile.
If there is nothing to connect, the dialog should not be shown.

### Extra points:
It would be good to have an easy way for the player to switch ammo for a projectile weapon. I imagine adding an option to the right click context menu for missile weapons where one could choose among the available projectiles in a dialog.

### Added notes 2022-07-17 Using rqid
Switching to using a rqid to connect the weapon to a projectile would make it possible to create a world weapon item that points to a rqid of a projectile. When that weapon item is embedded in an actor we can search for that rqid in the actor to connect the projectile to the weapon if the projectile also is embedded in the actor.

### Final solution
Using rqid was the wrong idea here since you might have two sets of arrows that might have the same rqid. Just display a dropdown with all equipped projectiles. Also show a input field for weapon quantity for projectile & thrown weapons.

**Comment by Moonpile** [comment]
Does this duplicate or replace #126?

**Comment by wake42** [comment]
It does, I'll close #126 I didn't find it when I searched before...

**Comment by Moonpile** [comment]
See also #492
