### ISSUE TITLE
Can't toggle experience from Combat context menu for weapon

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#163]
If you right click on a weapon in the Combat grid to pull up the context menu, it shows "Toggle Experience" but if you click it, it can't find the skillID in the data-set.  
![image](https://user-images.githubusercontent.com/3959760/148611328-e3a1f405-ad83-4d03-9659-327fad44116f.png)

If you right click on the same weapon but over the "Chance" column it works:
![image](https://user-images.githubusercontent.com/3959760/148611310-f6c0260f-7296-418d-b8da-e16c7231d47e.png)

**Comment by wake42** [comment]
They bug is that you should only get the toggle context menu on the usage section since each use represents a separate skill.
