### ISSUE TITLE
bug Deleting an opposed rune messes up the layout

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#164]
![image](https://user-images.githubusercontent.com/3959760/148628787-7f995399-7ffd-4436-a163-76e74aab7914.png)

I would expect the remaining rune, which is now missing its opposing rune, to just stay on its own line, maybe with the arrow and a placeholder.

**Comment by Moonpile** [comment]
Also, if you try to improve the now unlinked rune it just works but never seems to fire the "adjustOpposingRuneChance" method in rune.ts.  I couldn't even seem to get into the "preUpdateItem" method of rune.ts.  

Is this dead code?

**Comment by wake42** [comment]
I think that if there is no opposing rune it doesn't do the call if I remember correctly.
The layout needs to be redone completely since it uses hardcoded item names to figure out what to display where, see #123

**Comment by wake42** [comment]
Closing this case as issue #123 addresses the same issue.
The issue with updating the opposing rune is also fixed in #182
