### ISSUE TITLE
bug Wounds and location hit points reset on system refresh

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#165]
Here I've added several wounds:

![image](https://user-images.githubusercontent.com/3959760/148664120-0fe521d6-c0f3-46c0-85e9-d784cfe6f8f5.png)

After refreshing (F5):

![image](https://user-images.githubusercontent.com/3959760/148664132-0d15c819-9553-4aae-b17d-edc1d9d5a1cd.png)

The wounds are gone, the location hit points are back to max, but the location still says "wounded".

**Comment by Moonpile** [comment]
I was working on localization when I found this and the "RQG.Actor.Health.HitLocation" will be fixed.

**Comment by wake42** [comment]
That is something I haven't noticed before - but I could reproduce it. Apparently the wounds are not persisted? I think it has been before.

**Comment by Moonpile** [comment]
I was unable to reproduce this behavior.  

However I found bug where if the actor is wounded in a way that causes a status effect like "unconscious",  and then healed, the healing heals the wound but adds another copy of the status effect.  This is reported in #183

**Comment by Moonpile** [comment]
Closed as invalid
