### ISSUE TITLE
Background "tab" can be pushed beyond the scroll

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#170]
![image](https://user-images.githubusercontent.com/3959760/150603033-ee58bf2d-632b-4b3f-b654-346be44f1ce6.png)

If you (somehow) have Spirit Magic, Rune Magic, and Sorcery, then you have to scroll to see "Background".

Make less space between the sidebar tabs.

Make the default character sheet size configurable?

**Comment by wake42** [comment]
I think this might be fixed already. Need to verify though

**Comment by Moonpile** [comment]
I no longer think this is a real issue.  Yes, if you have ALL THE TABS then Background hangs down, but what else is it supposed to do?  Also you'd probably have more notes on a character like that and it wouldn't look weird.  I recommend we just close this.

**Comment by Moonpile** [comment]
Closed as invalid
