### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by lozanoje** [sun-dragon-cult/fvtt-system-rqg#181]
![](https://i.ibb.co/CzbSyVg/2022-02-10-17-45-24-Window.jpg)
![](https://i.ibb.co/wCVFcRp/2022-02-10-17-47-29-Window.jpg)
![](https://i.ibb.co/hWNWZzf/2022-02-10-17-50-00-Greenshot.jpg)
Passion creation:
![](https://i.ibb.co/3MSKBNy/2022-02-10-17-51-04-Greenshot.jpg)
Combat chat card:
![](https://i.ibb.co/nBMwB5p/2022-02-10-17-52-15-Window.jpg)
Rune spell chat card:
![](https://i.ibb.co/GCmRT2z/2022-02-10-17-53-19-Window.jpg)

**Comment by Moonpile** [comment]
![image](https://user-images.githubusercontent.com/3959760/159178435-215812ce-8404-4da8-8642-e49b39255c66.png)

This one is localized already.

`{{localize "RQG.Actor.Attributes.EncumbranceAbbr"}}`

**Comment by Moonpile** [comment]
Ok, I found out the starter set overrides the localization.  I've put moons at the start of everything and will address each of the concerns above with a "before" and "after" screenshot for my own sanity.

![image](https://user-images.githubusercontent.com/3959760/159179748-7e142752-a9b9-47cf-869f-eb16b0fe5985.png)
![image](https://user-images.githubusercontent.com/3959760/159179829-8b722c8f-bc68-4604-a90a-046ed3c2e41f.png)

**Comment by Moonpile** [comment]
Skill categories appear to be working
![image](https://user-images.githubusercontent.com/3959760/159179879-4a9c50c0-263a-4e58-81be-ee1d091b181a.png)

**Comment by Moonpile** [comment]
"Carried" tool tip in currency is working
![image](https://user-images.githubusercontent.com/3959760/159180103-81287895-aba3-41b2-a0ab-64206ad2e442.png)

**Comment by Moonpile** [comment]
"Equipped" tool tip is working in weapons and armor.  I checked all states in both grids.
![image](https://user-images.githubusercontent.com/3959760/159180201-06557a35-8590-4e66-bb20-2b91085c1a35.png)

**Comment by Moonpile** [comment]
Passions list looks wrong.  

![image](https://user-images.githubusercontent.com/3959760/159181256-0bee3488-ed61-4b36-be0d-4b6be75751e5.png)

But that's just because the emoji doesn't show up in the select options.

![image](https://user-images.githubusercontent.com/3959760/159182631-0afdbbf4-e666-4f88-ae36-1f6ae6667628.png)

**Comment by Moonpile** [comment]
Weapon chat card works.
![image](https://user-images.githubusercontent.com/3959760/159183478-aa257df9-d3e8-4096-bfd0-c5aaabb36b30.png)

**Comment by Moonpile** [comment]
And the Rune Magic Spell chat card and result card are working.

![image](https://user-images.githubusercontent.com/3959760/159183620-f4e20986-22e1-452d-bc72-10cce23ea466.png)
