### ISSUE TITLE
Healing Duplicates Status Effect

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#183]
Initial wound:
![image](https://user-images.githubusercontent.com/3959760/153603797-c2210a8e-9f8d-4fa9-b59f-db51f3e226d3.png)

Healing:
![image](https://user-images.githubusercontent.com/3959760/153603877-464025c4-6df4-4c9d-8a69-e60ae9b24864.png)

Results in fully healed with text status effects cleared but the token status effect is duplicated:
![image](https://user-images.githubusercontent.com/3959760/153603969-116a2a9b-3777-4724-b6e9-f8cf592d0a44.png)

**Comment by Moonpile** [comment]
I think it's clear we don't want healing the wound to add another condition, but do we want healing the wound to automatically remove the condition or do we want to leave that up to the GM?  I'm leaning toward leaving that up to the GM, or maybe prompting "Remove condition?" when healing.  Do we only remove the condition when fully healed?  Or remove it when healed above zero?

**Comment by wake42** [comment]
I think it should remove it automatically since it is added automatically. There is (apparently broken) code that should take care of that in hitLoctionSheet (setTokenEffect).

**Comment by Moonpile** [comment]
Yes, but remove only if fully healed?  Or remove if healed above zero?

**Comment by wake42** [comment]
I've interpreted it as above zero. You start getting these effects when you go below zero.
https://github.com/sun-dragon-cult/fvtt-system-rqg/blob/8f3d32cf80eafc1d0011ecab9d40702d64b7767d/src/system/healingCalculations.test.ts#L175

**Comment by Moonpile** [comment]
Making the title shorter because it makes my branch name too long!
