### ISSUE TITLE
When wounded, color the current HP on both location and total hit points to indicate status

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#184]
Could this just be as simple as whenever the HP in the location or total are below max that the current HP be red?  Or do we want a different color for "wounded but not incapacitated"?

This mockup was done by changing the element style.  The current/max for the location are in one span.  Not sure we want the "/" or the max to be red.

![image](https://user-images.githubusercontent.com/3959760/153605057-4ef21a34-6211-4136-aabf-bbf16e40c1bf.png)

**Comment by wake42** [comment]
Seeing this I wonder if only the "wounded" text should be red instead of coloring the numbers? That would also stand out - maybe even more as the text is larger than then numbers.

**Comment by wake42** [comment]
Experimented a little, how about this look? `(color #cf0000)`

<img width="297" alt="image" src="https://user-images.githubusercontent.com/4853677/153732189-99f0f1d3-ed9c-4eea-9ae3-830087e09bfa.png">

**Comment by wake42** [comment]
Implemented in #605
