### ISSUE TITLE
Healing Dialog can break actor

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#198]
The healing dialog don't auto select any wound (radio button) - meaning the heal function don't get a wound index which breaks the actor while trying to apply the healing.

**Comment by Moonpile** [comment]
I believe I covered this with the point "have one of the wounds pre-selected in the radio buttons (the biggest? the first?)" in #195

**Comment by wake42** [comment]
OK missed that part. Looking at this now so will soon fix that to begin with at least.
