### ISSUE TITLE
Create Occupation Item

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#203]
### _Why:_ Is your feature request related to a problem?
To make creating an extensible character wizard #101 possible we need a way of storing different occupations and their impact on characters. Adding an occupation item would make it easy to include a set of homelands in one or more compendiums.

### _What:_ Describe the solution you'd like
The Occupation item should contain
- Description (large text) link to journalEntry
- ~~Homelands (list of "Homeland" items by ID? or just text?~~
- Occupational Skills (map of "Skill" items by Compendium ID and bonus as integer and whether or not the skill is used for income)
- Standard of Living (text, fills in field on background tab)
- Base Income (text, fills in field on background tab)
- Cults (list of "Cult" items by ID? Or just text?)
- Favored Passions (list of "Passion" items by ID?) (player chooses one at +60% or increases one they already have by +10%)
- Ransom (text, fills in field on background tab)
- Equipment (list of "Armor", "Gear", and "Weapon" items by ID)

### Additional context
If we're making an "Occupation" item type, do we just have a slot on the Actor for an array of Occupations and render them that way? On the actor we would only need to render the description, standard of living, base income, and ransom. During creation there needs to be some way to add the skills (or update existing skills), add a cult (optional as this could have been done under Homeland already), add or update a favored passion, and copy all the equipment over to the Actor.

### Related to
- [x] #202

### Blocks
- [ ] #101

### Blocked by
- [x] #199

**Comment by Moonpile** [comment]
I think the Homeland should have a list of Occupations but it doesn't need to be the other way around.
