### ISSUE TITLE
Spirit Magic Duration "Focused" does not set Concentration to "Active"

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#208]
### _What_: Describe the bug
When you change the Duration of a Spirit Magic spell to "Focused" it should set the Concentration to "Active".

### _How:_ To Reproduce
1. Go to the Spirit Magic Item Sheet
2. Set Duration to "Temporal" and Concentration to "Passive"
3. You should see "Passive" in the Spirit Magic grid on the Actor Sheet.
4. Change Duration to "Focused"
5. You will see the Concentration select on the Item Sheet has changed to "Active" but the Spirit Magic grid on the Actor Sheet still says "Passive".

### Expected behavior
Changing the Duration to "Focused" should always set Concentration to "Active".

### Screenshots

Step 3
![image](https://user-images.githubusercontent.com/3959760/157904958-84c336b9-25e3-4ed0-aebb-70867a124a32.png)

Step 5
![image](https://user-images.githubusercontent.com/3959760/157905189-27f72668-daa7-47d2-8f77-f2a8da7ceb8e.png)

### Environment - please paste the information from foundry settings tab "support" button:

DEV branch for issue #199 

Foundry Virtual Tabletop: Version 9, 9.254
Game System: rqg, 1.14.0
Active Modules: 1
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.15.1179)
Max Texture Size: 16384

Scene: 6000 x 4600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 1 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 1

Actors: 1 | Items: 53 | Journal: 4 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 37 | Chat Messages: 4

**Comment by Moonpile** [comment]
@wake42  I'm unable to reproduce this now.  Can you confirm?

**Comment by wake42** [comment]
No I can still reproduce the bug. 
![image](https://user-images.githubusercontent.com/4853677/159343592-7d3f857d-d398-4f2b-8aae-18d41c6447bd.png)

When I close the spirit Magic sheet the Concentration text disappears
![image](https://user-images.githubusercontent.com/4853677/159344088-f1608994-e16a-4dfd-9997-38480297ed08.png)
