### ISSUE TITLE
Allow players to add Passions

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#218]
### _Why:_ Is your feature request related to a problem?
When a player gains a passion they should be able to add it themselves.

### _What:_ Describe the solution you'd like
Add a button that adds a new embedded passion to the actor. The passion sheet should open to allow the player to edit what kind of passion it is.
![image](https://user-images.githubusercontent.com/4853677/159135304-9d9be9c4-887c-44a1-b2b0-d77627fd39d9.png)

### _Options:_ Describe alternatives you've considered
Should it also be possible for the player to delete passions? ~~That could maybe be reserved for the GM~~. Yes make the delete context menu visible for players as well!

**Comment by Moonpile** [comment]
The easiest thing is to just add a completely new Passion to the Actor but that will result in a Passion that does not have an rqid that matches a "pre-defined" passion.  And I think this route should be an option no matter what, even if we also have a more complicated way of adding by rqid.

If we have "Loyalty (Sartar)" as a pre-defined Passion in a compendium somewhere, but a player adds it and sets the name to "Loyalty (Sartar)" and we ever want to look for "i.passion.loyalty-sartar" on that Actor we will not find the one they added.

So I guess the question is how far do we want to take this?  I'm going to start by doing the simplest just add a new Passion option and we can go farther if we think it's needed.

**Comment by Moonpile** [comment]
Another way to do this is that if the player is an Observer (at least) of a Passion, the player can simply drag a Passion on to their Actor sheet.

**Comment by Moonpile** [comment]
And this raises the question that we don't have a similar "+" add button for skills, runes, spells, or anything else really.  Do they need them too?

**Comment by wake42** [comment]
About the rqid - it's hard to auto generate them, it kind of works in English but not for any other language. That is a general problem with the rqids I think. Maybe they are basically only for system / module provided items...

**Comment by wake42** [comment]
> And this raises the question that we don't have a similar "+" add button for skills, runes, spells, or anything else really. Do they need them too?

I think in those cases they should really be dragged from the system provided versions, providing a + button might weaken the rqid system I think

**Comment by Moonpile** [comment]
Yeah, I do think Passions are the most likely to be entirely "unique", for example "Love (Esmelda)" or something.  I'm going to do the simplest possible thing and just add a new one and let the player edit it (or delete from context menu).  They can still drag from a compendium or world items if they can see them.
