### ISSUE TITLE
#101 Subtask: Step 0 Choose Species

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#230]
On the alternate character sheet for Adventurer creation, allow the player to choose a species.  These will be defined as "template" actors in a specific compendium.

- Should there just be one canonical compendium where we put templates?
- Configuration allowing multiple compendia to search through?
- Maybe the actor can have an "isTemplate" property and we can look through all the compendia for an actor where isTemplate is true?

See #101

**Comment by wake42** [comment]
How do we want this to work if we say that we should have different template actors for each species. That would mean the act of choosing species is actually the GM duplicating a specific template actor for say human or duck. You wouldn't be able to change template afterwards I think. Or do you envision having a "plain" actor without anything, and then copying items / characteristic formulas etc from a selected species template actor?

**Comment by Moonpile** [comment]
As of right now I imagine the "template actors" just being plain actors.  Perhaps marked with isTemplate=true if that helps us find them.  When you choose a template from the "Step 0: Species" tab, it copies in the characteristic formulas, hit locations, and the most basic skills with their default Base Chance.  This will not include skills that you get from your Homeland culture like "Speak (Heortling)", though it will include skills that (almost) everyone gets but which the Homeland culture modifies, like "Dance".

I think if you were to choose human and then later choose dwarf we'd have to diff the skills so we can see if the player has added to them from Step 5 Occupation choices or Step 7 Personal Skill Bonuses or somewhere else.  This part could be difficult and is a general problem with the whole thing really.

Example of Homeland skills starting on page 60 of RQG
![image](https://user-images.githubusercontent.com/3959760/160263519-bd267fb5-fdf6-4899-9bcd-0ee557c27fd4.png)

**Comment by wake42** [comment]
I think that sounds good. Also an added benefit of the template actors is that if the GM for some reason don't want to use the wizard, he can just grab a template actor and start dragging stuff to it manually.

**Comment by Moonpile** [comment]
I'm going to implement this with a method that looks in a specific compendium for the actor templates.  We can change the underlying method of getting them if we want.  Some ideas:

- Just return all the actors in a specific compendium (what I'm going to do for now)
- Return all actors from a list of compendia
- Return all actors from world or compendia that meet some criteria (isTemplate = true)
- Implement rqid for Actors and have like "actor-human-template" and look for the "best" ones by rqidpriority
