### ISSUE TITLE
JournalEntryLink to RqidLink

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#255]
Wherever it makes sense convert JournalEntryLink properties and controls to RqidLink.

- runeData
- runeMagicData
- skillData
- spiritMagicData

The following will be done during their "steps" in Actor Wizard (assuming this is not done first).
- homelandData #231 
- occupationData #232 
- cultData #236

**Comment by wake42** [comment]
Fixed by #293
