### ISSUE TITLE
Impossible to change Cult Name

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#333]
### _What_: Describe the bug
The Cult Sheet does not allow the user to change the Cult Name

### _How:_ To Reproduce

Create a new cult with any name:
![image](https://user-images.githubusercontent.com/3959760/185749383-40659b68-4486-4be1-8565-cf71ed4158e4.png)

Change the Cult Name field
![image](https://user-images.githubusercontent.com/3959760/185749460-94d22573-6c93-45f3-8376-a747ad6f1a26.png)

Move focus to another field and the Cult Name reverts to the original name.
![image](https://user-images.githubusercontent.com/3959760/185749483-df471e4d-f713-40e2-9302-a57d4f063a7a.png)

### Expected behavior
Editing the Cult Name should change the name of the cult.

### Screenshots
See above

### Environment - please paste the information from foundry settings tab "support" button:
Foundry 9

### Additional context
n/a

**Comment by wake42** [comment]
Already fixed in #318
