### ISSUE TITLE
Remove `- category` from skill names

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#335]
Now skill names have the structure of `<skillName> (<specialisation>) - <skillCategory>` 
For example `Worship (Orlanth) - magic`. This poses a problem with respect to translation since the skillCategory basically is a enum value. It also makes the lists of skills look bad in various places like the character creator and chat messages.

The upside of adding the skillCategory is that it makes it easier to search for skills in the world and compendiums, but both the the future compendium browser #201 , and the character creator will reduce then need / make it easier to search for skills. 

Remove the skillCategory ending in the system and in the compendiums. 
One thing to think about is if it could make default rqid collide for journal links like je..skillname

**Comment by TheChaosium** [comment]
There is no collisions on the skillname for the journal like as the category is not part of the rqid.

**Comment by TheChaosium** [comment]
@wake42 I think you meant to do this on the RQ SS, not the system module. We haven't move the systems down.

**Comment by wake42** [comment]
System and SS both. The name is created automatically when you create a skill, so that code needs to be changed as well as the skill names in SS and system packs.

**Comment by TheChaosium** [comment]
OK, I have the creation sorted. I'll update all the current system places too (that is more of a search and replace).

**Comment by TheChaosium** [comment]
Not sure about any upgrade. Do we have a script that removes them from copied skills? Does it matter?

**Comment by wake42** [comment]
Yes there need to be a migration script as well that removes the category from all items in active worlds. There is an example item migration here that can be a start (as well as other real ones in the same folder) https://github.com/sun-dragon-cult/fvtt-system-rqg/blob/master/src/system/migrations/migrations-item/migrateItemDummy.ts
The new item migration function needs to be added here to so it is applied to all items in the world https://github.com/sun-dragon-cult/fvtt-system-rqg/blob/1f36e189c4340c368dee73a41f06896706ee327b/src/system/migrations/migrateWorld.ts#L54-L62
