### ISSUE TITLE
Extend rqid to handle embedded documents

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#353]
To be able to reference for example item embedded in an actor, or pages in a journal there needs to be a way to reference embedded documents with a rqid. 

Foundry has implemented something similar for UUID: https://github.com/foundryvtt/foundryvtt/issues/7415#issuecomment-1184793714 The relative notion is not applicable to Rqid though. A rqid in an item could be resolved to either a world/compendium document or a sibling embedded document without any extra syntax. For example a rune referencing another rune by rqid would find an embedded item instead of a world item.

This needs some experimentation but an initial proposed syntax could be `a.character.nisse.i.skill.act` with the second part being optional. ~~To allow linking to page headings an additional extension could be provided for page (p) links. `je..rune-descriptions#air-element` or `je..wiki.p.text.runes#air-element`~~ This is not doable since the heading is an already translated string, so it cannot be used as a language agnostic reference to the heading.

**Comment by Moonpile** [comment]
Aside from linking to a specific page of a journal (which would be nice), what's the purpose of this?  rqid is for finding the "best" document, right?  That should never be a document embedded in something else.  It should either be in the "world" or in a compendium.

**Comment by wake42** [comment]
The main purpose is definitely to be able to handle page documents that are embedded inside journalEntry documents. I just think being general is better since rqids are general to document. If it's solved for journalEntries with pages, then it might as well work for actors with items or whatever. That should lead to less special cases.

My idea is that you find the matching enclosing document with the best prio and then do another search inside that document for matching documents that are embedded.

**Comment by wake42** [comment]
closed by b3470b6f946d09ccc4fbf1608edd23ae33eb8143
