### ISSUE TITLE
Create labels for hit location names per body type

### ISSUE THREAD

**Issue by TheChaosium** [sun-dragon-cult/fvtt-system-rqg#378]
### _Why:_ Is your feature request related to a problem?
To support internationalization we need to be able to have the hit location names as labels

### _What:_ Describe the solution you'd like
Add the hit location names to openSystem.json and reference them as needed.

### _Options:_ Describe alternatives you've considered
None

### Additional context
No

**Comment by wake42** [comment]
This is included in #260
