### ISSUE TITLE
Review the setting with hitlocation names

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#380]
Currently there is a setting with a list of available hit location names. This is a bit awkward - evaluate other solutions.

One possibility could be to gather all hitlocation items using rqid and generate the name list from them. The downside would be that at least one hitlocation of each name would have to be part of a compendium, and the current idea is to have hitlocations for different species embedded in template actors.

**Comment by Moonpile** [comment]
An argument in favor of having a "Hit Locations Compendium" is for creating your own creatures as a GM.  It allows you to drag them from the compendium to the Actor sheet.  Of course if there's a "+" button in the hit locations then you can just click that and it can add one by Rqid or let  you create an entirely new one.  And adding it by Rqid requires the compendium anyway.

Of course having a "Hit Locations Compendium" increases our compendium bloat.

**Comment by wake42** [comment]
## Problems with current solution
- Unintuitive and cumbersome to have to add available hitLocation names in a setting
- Translations of hitlocation names are not possible. Also translation of items can't be part of the runtime Foundry translations (game.i18n.localise).

## Limitations / constraints
- Armor items needs to reference HitLocation items. Currently done by hitLocation name, but that is problematic (see above)
- HitLocations of creatures of the same body type are not the same. They (might) have different natural AP.

## Suggested path forward
- Change the armor -> hitLocation link to use rqid instead of name. This will make it possible to translate the name since it's no longer used as an ID.
- Include compendiums with sets of hitLocations per body type, but with natural AP set to 0. These compendiums would be translated compile time and a separate compendium per language will be generated (that build system is already in place). Later modules could provide additional body types.
- Include a macro for the GM to set the natural AP of all hitLocations in an actor. Prompt for what value they should get. (*** TODO Check how common different AP / hit locaton is ***)
- At system start (GM), scan the world for available hitLocations (rqid + name) and store a list of those. Similar to how available runes are detected now.

## Downsides / questions
- Is a compendium with body types needed? What is the benefit compared to having a template actor complete with appropriate hitLocations, runes, skills etc. There currently exists compendiums for `human-hitlocations` & `pc-runes` but skills are not broken into PC-skills and others. How should new actors (PC & NPC) be created? Is the character creator only for PCs, while NPCs (including creatures) should be assembled by dragging items to an empty actor? 
- If we use rqid to link armor to hitLocation then any new hitLocation a GM creates needs a rqid, and those are not created by default. Since it's very important that hitLocations have a rqid, there should probably be some kind of notification / check in the hitLocation Sheet to make sure a rqid exists. The autocreate rqid function really only works when using the system in english, since the rqid names are supposed to be in english. This is a general limitation/problem of rqid.

## Example user flow after change

### Adding a hitLocation to an armor item
No visual change compare to current flow

### Creating a new hitLocation item
*now*
First add the name of the new hitLocation in the hitLocation settings. This makes it available both in armor coverage and hitLocation name.
Then select that name in the hitLocation sheet.

*after change*
The hitLocation sheet name input field could have a datalist dropdown populated with suggestions from already existing hitLocations, but it should also be possible to enter any name. 
A very visible warning should be shown if the item does not have a rqid, since if there is none, then the hitLocation will not be possible to add to an armor item as "protecting". Note you could possibly create a hitLocation with a rqid that claims it's a head, but name the hitLocation "left leg". Maybe the rqid should be made more visible for this item type? Or should that be a general change that all item sheets displays the rqid & language a little more upfront?

## Tangentially related
When adding hitLocations to an actor it might be good to display a warning if not all die-ranges (d20) are covered or if multiple hitLocation cover the same die roll.

**Comment by wake42** [comment]
As for compendium bloat I think that will be solved in Foundry 11 where you can have folders in the compendium. So maybe it's a good idea with hit location compendiums for each body type.

**Comment by TheChaosium** [comment]
I think that by the time the bestiary is released we will have most body types and the number of new ones will be small.
