### ISSUE TITLE
Skill Base Chances

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#412]
### _What_: Describe the bug

Some skill base chances are incorrect.  This issue is for accumulating them and fixing them all at once.

### _How:_ To Reproduce

n/a

### Expected behavior

- Farm - Page 61 and Chaosium Character Sheet lists it as base 10. Foundry Sheet and Page 177 has base 5
- Kick - Page 61, 208, and Chaosium Character Sheet lists it as base 15. Foundry Sheet has base 25  (This also looks like the name is just "Melee Weapon" when dragged from a compendium to an actor sheet).
- Many compendium skills have a "learnedChance" property with a non-zero value.  These need to all be changed to "gainedChance" with value of 0 (zero)

### Screenshots

n/a

### Environment - please paste the information from foundry settings tab "support" button:

Core Version: 10.291

System: rqg 2.0.1 (Sun Dragon Cult, Wake, Moonpile)

**Comment by Moonpile** [comment]
So far I've been through all of the skills listed on the Base Skill Values EXCEPT for any weapons that aren't Fist, Kick, and Grapple.

**Comment by wake42** [comment]
As for `Fist (Fist)` that follows the pattern for other weapon skills like Javelin or Sling
![image](https://user-images.githubusercontent.com/4853677/210497142-5e95eb18-88ed-40df-84d8-083d714ff7b8.png)
![image](https://user-images.githubusercontent.com/4853677/210497425-62ac64c0-9876-47ef-9bad-085ad3d2d6c6.png)
The skill name is the "Category" (you should get 1/2 chance of any weapon with the same category you pick up) and the specialisation is the weapon "Name" that should more or less match the weapon item name (you can of course name your weapon whatever, but the generic name). 

I agree that things like `Fist (Fist)` looks a bit odd. Maybe the categories should be in plural? Would `Fists (Fist)`, `Javelins (Javelin)` & `Slings (Sling)` maybe make more sense? Then the other categories would be like `1H Axes (Battle Axe)`, `Bows (Composite Bow)` & `2H Spears (Pike)`.

**Comment by Moonpile** [comment]
I am unable to reproduce the issue where the "Kick" skill looked like its name was just "Melee Weapon" after dragging it from the compendium to the Actor.
