### ISSUE TITLE
Silent Initialize All Characteristics for GM

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#418]
### _Why:_ Is your feature request related to a problem?

As the GM, I don't want to put chat cards into the chat log when I initialize characteristics on an NPC because it lets the players know what I'm doing.  Also, I might be doing a lot of initializations and don't want to have to delete all the results.

### _What:_ Describe the solution you'd like

Either the GM always initializes silently, or maybe there could be a "Do this without chat cards?" prompt?

### _Options:_ Describe alternatives you've considered

Setting the roll mode to private makes sure that the players don't see the rolls, but I think they might still hear them.  Regardless, I just don't want or need the cards unless a Player is doing the initializing.

Maybe there could be an "Initialize All Silently" context menu option that only the GM can see?

### Additional context

n/a

**Comment by Moonpile** [comment]
@wake42, personally I think that if the GM does "Initialize All" it should just always be silent.  That way we don't need a setting, or a different context menu item.  What do you think?

**Comment by wake42** [comment]
Yes I guess we don't really need a chat saying that characteristics have been rolled.
