### ISSUE TITLE
Evaluate Initialized Characteristics

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#420]
### _Why:_ Is your feature request related to a problem?

**Note: I'm fully aware that this is a way out there feature request.**

As a GM, when I initialize all characteristics on an NPC, I'd like some quick visual indication about if this instance of the NPC has particularly good, normal, or particularly bad characteristics.  For example, the PCs are at a horse merchant and I drag several horses out into the stalls.  They're using Animal Lore to look for ones with high CON and STR and succeed so I can just quickly look at the visual indicators to pick out the "best" horse for them.

### _What:_ Describe the solution you'd like

See above.

### _Options:_ Describe alternatives you've considered

The alternative is doing some math in my head quickly or just changing the stats on the horse to be better.  However, if you have "4d6+12" it takes a moment to figure out what a "good" stat is versus a "very good" stat.

**Comment by Moonpile** [comment]
This is also in line with the idea of having a view for skills (and runes) that the NPC has "experience" in so that at a glance the GM can know what a randomly generated NPC is "good at".

**Comment by wake42** [comment]
I like that idea - just have to figure out a nice way of illustrating it without taking over and cluttering the character sheet. 

Partially related, for the usecase of "dragging horses to a stable" should there be a easy way of converting them to linked actors as well? Since when you buy a specific horse that should the keep it's characteristics.

**Comment by Moonpile** [comment]
> I like that idea - just have to figure out a nice way of illustrating it without taking over and cluttering the character sheet.

Colored background for the stat number?  This would only be for the GM.

> "dragging horses to a stable"

I'm using the Actor Link Indicator mod in my campaign to just remind me what I'm looking at.  https://foundryvtt.com/packages/actor-link-indicator

I meant literally dragging them onto a stable scene which would instantiate temporary "token" actors.  Are you suggesting that we find a way to move the "generated" token Actor back to the "world" as a linked Actor.  So I drag out five horses, you evaluate them, pick the one you want to buy, and then I do something that sends it back to the "world" as a linked Actor where I can give you ownership of it?  If that's what I'm to understand, yeah, that would be a great follow up feature.

**Comment by Moonpile** [comment]
I envision making for myself a lot of templates like "Sartarite, Clan Warrior, Light Infantry" or "Sartarite, Clan Warrior, Skirmisher" and so on with many, many variations for all kinds of people and creatures.  They'd have a more tightly constrained dice expression so that you're not generating STR 7 Heavy Infantry.  Now that I understand what you were getting at with the auto-initialize I really like the concept.  Anything we can do to make that "cooler" I'm on board with.

**Comment by Moonpile** [comment]
This should be very easy with https://foundryvtt.com/api/classes/client.Roll.html#evaluate

Now we'll often be comparing a bell curve distribution to a flat percentage of the range but I think that's "good enough" for the purpose.  I don't need to know what percentile they're in of actual results of the roll, just a general sense of "This wolf is of average SIZ" or "this guard has very good DEX".

**Comment by wake42** [comment]
> I meant literally dragging them onto a stable scene which would instantiate temporary "token" actors. Are you suggesting that we find a way to move the "generated" token Actor back to the "world" as a linked Actor. So I drag out five horses, you evaluate them, pick the one you want to buy, and then I do something that sends it back to the "world" as a linked Actor where I can give you ownership of it? If that's what I'm to understand, yeah, that would be a great follow up feature.

This is definitely some other case, and I'm not sure I know how it should work or how useful it would be, but something like that maybe. This could definitely wait til later though...
