### ISSUE TITLE
Healing Context Menu Options

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#423]
### _Why:_ Is your feature request related to a problem?

As a GM, I would like to be able to quickly, fully heal a character, and also to quickly fully heal a specific hit location.

### _What:_ Describe the solution you'd like

In the Hit Points area, I would like a context menu option that says "Full Healing" or something like that. Choosing this menu option deletes all wounds, conditions, and sets current HP to max HP.

For each Hit Location, I would like a context menu option that says "Fully Heal <<Head>>" or whatever the location name is.  Clicking this menu option removes all wounds from the location and adjusts the current "genera" HP accordingly.

A stretch goal might be to have a context menu option that says "Heal One Week" that applies the weekly healing rate to the character following all the rules for that.

### _Options:_ Describe alternatives you've considered

Manually removing wounds, conditions, and setting HP to max takes several steps.

### Additional context

n/a

**Comment by Moonpile** [comment]
I started in on this and quickly ran into a few things I'd like to discuss before taking it further.  I'll put one idea per comment so that you can reply to them separately.

**Comment by Moonpile** [comment]
I think the Fully Heal location could easily be handled instead of the context menu by making the existing heal wound dialog allow for check boxes instead of radio buttons.

![image](https://user-images.githubusercontent.com/3959760/212381766-319112a0-c987-4ed1-8dae-71851c14b444.png)

For each wound there would have to a check box, the number of hit points of the wound, and a text box for how many to heal on that wound.

The dialog could just have an "Heal All" button that just fully heals all of them.

**Comment by Moonpile** [comment]
The healing functionality is currently in hitLocationSheet.ts.  I feel like healing should actually be a function (or functions) on actor.ts since it's not just the location that is affected.  Healing the location heals the actor's total hit points as well and may change status effects.

So what I'm suggesting is having one or more healing methods on actor.ts that we use from the context menus and dialogs as needed.

**Comment by Moonpile** [comment]
I think a really neat and helpful idea would be to extend the wound array on hit location so it's not just a number.  I'm thinking a wound should have the following properties:

- descriptive origin (ie "Tusker Spear" or "Twisted Ankle")
- hp  
- Sealed?  check if the wound has been affected by Seal Wound and must undergo natural healing
- Scar (for after the wound is healed, maybe it leaves a scar, not sure how we'd display this though)

**Comment by TheChaosium** [comment]
That maps to my version for Pendragon. No hit locations, but an array of wounds that you can track independently as each can get first aid.

**Comment by Moonpile** [comment]
If we want to do what I'm suggesting here, do we break this up into separate issues, and if so how?

**Comment by wake42** [comment]
> I think the Fully Heal location could easily be handled instead of the context menu by making the existing heal wound dialog allow for check boxes instead of radio buttons.
> 
> ![image](https://user-images.githubusercontent.com/3959760/212381766-319112a0-c987-4ed1-8dae-71851c14b444.png)
> 
> For each wound there would have to a check box, the number of hit points of the wound, and a text box for how many to heal on that wound.
> 
> The dialog could just have an "Heal All" button that just fully heals all of them.

Yes I agree - a "Heal All" button in the current heal dialog is probably the best solution. Should there be two extra buttons? One for "heal all in this hit location" and one for "heal all wounds on character"?

**Comment by wake42** [comment]
> The healing functionality is currently in hitLocationSheet.ts. I feel like healing should actually be a function (or functions) on actor.ts since it's not just the location that is affected. Healing the location heals the actor's total hit points as well and may change status effects.
> 
> So what I'm suggesting is having one or more healing methods on actor.ts that we use from the context menus and dialogs as needed.

I agree that it's in a strange place now. But I think a `healWound` function should be located on hitlocation Items since the wounds are located in those items. They will always be embedded so it's easy te get the actor with `item.parent` to find what actor should get totalHP healed.
The actor should have a function `healTotalHitPoints` though since that is where that exists.

Does that sound reasonable?

**Comment by wake42** [comment]
> I think a really neat and helpful idea would be to extend the wound array on hit location so it's not just a number. I'm thinking a wound should have the following properties:
> 
> * descriptive origin (ie "Tusker Spear" or "Twisted Ankle")
> * hp
> * Sealed?  check if the wound has been affected by Seal Wound and must undergo natural healing
> * Scar (for after the wound is healed, maybe it leaves a scar, not sure how we'd display this though.  Maybe just a list of scars and their origins below the hit locations?)
> 
> If we do this the Heal Wound dialog would also display the descriptive origin of the wound and maybe have a "Leave Scar" checkbox.

I like the idea of adding metadata to wounds. For the descriptive origin, where would that text come from? Eventually I think that it should be possible to drag a chat message with a hitlocation and damage roll to a token to apply the damage. When that is implemented, along with using Foundrys targeting system, we could add a lot of metadata to a wound. But until then, how do you envision we should get that data? A textfield in the add wound dialog?

What would the logic of when a wound would leave a scar be? Self healed wounds? Single wounds over a the hit locations HP? Should all the wound metadata be transfered to the scar array when the wound is healed? It sound like it is hard to do in a general way: 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4853677/212480218-585526e9-3c96-435f-9015-687d0f6cba6c.png">

For "sealed wound" is this basically a check if a First Aid has been attempted on the wound? If so then I think it might be hard to do in a good way since the act of rolling First Aid isn't in any way connected to any wound as it is now at least.

**Comment by Moonpile** [comment]
> For the descriptive origin, where would that text come from?

I was assuming the GM or player would enter the descriptive text.  They might want more or less flavor.  I'm not sure it needs to be automated, but dragging the chat message into the Actor sheet is a great idea that should "fill in all the numbers and at least get the description started".  Even fully automated though, I can see the GM or Player wanting to embellish this.

> What would the logic of when a wound would leave a scar be?

That's why the "Heal Wound" dialog should have a "Leave Scar?" checkbox.

> For "sealed wound" is this basically a check if a First Aid has been attempted on the wound?

Seal Wound is a spell you can cast that denies magical healing.  I think just a checkbox in the wound is enough reminder that it is Sealed magically.

**Comment by wake42** [comment]
Adding discussion from Discord. This issue should be split up into separate issues:

1) Refactor the code to be in a more logical place. Add a `healWound` & `addWound` method to the `hitLocation` item, and a `applyDamageToTotalHp` and a `healTotalHp` method to the actor.
2) Modify the hitlocation healing dialog to include a heal all wounds button
3) Make the "Healing rate 3/week" text clickable and open a dialog where you can either heal all wounds / total HP on the character or apply some timespan of healing.
4) Add wound descriptions to the `Add wound` dialog, and "leave scars" in the `Heal Wound` dialog

**Comment by wake42** [comment]
Closing since this issue is now split into separate issues.
