### ISSUE TITLE
Make it possible to rearrange physical items order

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#451]
### _Why:_ Is your feature request related to a problem?
As a player it would be good to be able to sort your gear, weapons etc so that the things you often use is at the top. 

### _What:_ Describe the solution you'd like
By sorting the items on item.sort and allowing drag'n'drop it's easy to allow players to rearrange the order of physical items (gear, weapon, armor). Also allow manual rearrange of passions.

While doing this, investigate a good way to visualise allowed drop zones.

### Additional context

Should there be a way to resort the items alphabetically?

**Comment by Moonpile** [comment]
I still am not a huge fan of items being "unique".  I think everything should just have an editable quantity like the consumables do now.  The "Gear" and "Consumables" sections are just pointless separation in my opinion.

![image](https://user-images.githubusercontent.com/3959760/214682777-ff445ad4-2512-4dd7-8625-280ac2878608.png)

**Comment by wake42** [comment]
I totally agree, see #211 it's planned for version 2.5
