### ISSUE TITLE
Show spirit magic spell "focus" on spirit magic tab

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#453]
There is a `spellFocus` property on the spirit magic item, but it's only shown in the item sheet. 

Show the `spellFocus` property in the table on the spirit magic tab.

**Comment by Moonpile** [comment]
What about the other way around?  What about putting something on any "gear" item that allows you to make it the focus for a spirit magic spell?  I'm thinking like a "Focus For" on the item:

![image](https://user-images.githubusercontent.com/3959760/214683554-1e7566f7-7395-4459-9c8d-ea159e52e06a.png)

**Comment by wake42** [comment]
The current `spellFocus` does not have any game mechanics built in since it's just a plain text field. I did toy with the idea of having it point to a physical item and if you did you could modify the time it takes to cast a spell depending on if that item is equipped or not. In the end I decided against it since I thought it would be too much hassle for the players. But maybe I'm wrong - would it be a good idea? 

I still think that field belongs on the spell and not on the physical item though. It should be possible for two spells to use the same item as focus, so having the field on the physical item would mean having an array of spell items there. And if we were to use it for deciding casting time it would be easier to have the link on the spell you are casting, compared to searching all embedded physical items for a reference to the used spell item.

As a side note, that would mean that you would have to have your tattoos as gear since you can have a tattoo as focus.

The `Attuned to` field is different I think since it's the actual physical item that is attuned to a character. That does not have any game mechanics either, since that too is only a plain text field. It could possibly be replaced with a uuid (or maybe rqid) to a character, but I'm not sure the gain is so large.

**Comment by Moonpile** [comment]
I was thinking creatively. It's probably fine to leave it as a text field on the spell and simply put the focus in the grid.  Mostly I was thinking of how to maximize the "flavor" of knowing that this spell's focus is a rattle, and this one's is a drum, or something like that.
