### ISSUE TITLE
Improve RqidEditor

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#457]
### _Why:_ Is your feature request related to a problem?

Only the last part of an rqid should be editable in the rqid editor, since the first parts are dependent on the documentName and type.

### _What:_ Describe the solution you'd like
Do something like this

![image](https://user-images.githubusercontent.com/4853677/214173245-00b61a5b-4970-48a3-8386-118914299bec.png)

Also think about the default value both for rqid and the priority. Priority could default to 0, but the rqid should not be set to something like `a.character.` just because the input field is empty.

**Comment by Moonpile** [comment]
As a GM when writing notes in the Text Editor, I want an easier way to add an RQID Link (see #301) to the text editor.  One way to do this might be to have a quick way to copy something like ```@RQID[i.weapon.composite-bow]{Composite Bow}``` from the RQID Dialog.

There might be another way to achieve this within the Text Editor, but the above seems like the simplest idea for now.

**Comment by wake42** [comment]
I didn't include that in the 2.1.0 release, but I hope to make it possible to drag documents to a text editor to get a RQID link - in a similar way that Foundry lets you drag and get a UUID link. This needs a little more research though, so a extra field in the rqid-editor sound like a good stop gap solution.
