### ISSUE TITLE
Move Compendium Localizations to separate file

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#459]
The "openSystem.json" file is getting very large.  It would be nice to have one file for the UI localizations and one for the Compendium localizations.

"buildPacks.ts" defines the file name to use for the compendium localizations.  That can be changed to something like "rqgCompendium.json", which could start as a copy of "openSystem.json".

Then we can remove the Compendium localizations from the UI part ("openSystem.json") and remove the UI localizations from "rqgCompendium.js".

Because we still may have localizations in the Compendia that might want to use values from the UI, perhaps "compendium-pack.translate" can fall back to "openSystem.json" if it does not find a localization in "rqgCompendium.json"?

**Comment by wake42** [comment]
I agree that the two types of translation keys should be split into separate files. The file containing the UI content keys will be loaded when running the RQG system, so only the UI keys should be in that one. The filename `openSystem` should probably be changed to something more descriptive like `uiContent.json` while the file for compendium content keys could be called `rqgCompendiumContent.json`.

The compendium-pack script could easily take two filenames and just concatenate the content of both files into the `dictionary` object that is used for translation. Maybe even allow splitting into more content files to separate further?

The filename is part of the content key when translating for compendium content (build time) so a key could look like `uiContent.RQG.Item.Armor.ArmorMaterial.HeavyLeather` ("Heavy Leather") or `rqgCompendiumContent.cult.aldrya.name` ("Aldrya").


The starter set and other modules should have a copy of the `uiContent.json` file, and probably of the `rqgCompediumContent.json` file as well so the translations can be referenced there as well. There will be a `SS.json` file for the compendium content specific the starter set module. So a key there could look like `SS.cult.aldrya.name` ("Aldrya"). A good way of keeping these files in sync is something that needs to be solved in the future.
