### ISSUE TITLE
Improve accessibility: experience marker too little contrast

### ISSUE THREAD

**Issue by phoenix-pnp** [sun-dragon-cult/fvtt-system-rqg#470]
### _Why:_ Is your feature request related to a problem?

Experience markers on skills, runes, etc. have too low contrast for people with color vision impairment or even on low contrast devices. Therefore, it is sometimes hard to tell if the skill has a marker or not.
As I myself suffer from red–green color vision deficiency I hadn't even seen the markers until a friend pointed them out to me ;)

### _What:_ Describe the solution you'd like

I favor two options:
1. change the color for properties with experience markers to something more distinguishable from properties without.
2. add an option to settings to enable tick boxes or similar next to the property, or to change to a a more accesible color scheme.

My preference would be option 1.

**Comment by wake42** [comment]
Added a white outline to make it more distinct. Also changed the red color to a darker shade that should be more visible for users with color deficiency.


![Image](https://user-images.githubusercontent.com/4853677/219619902-ed2a32be-e7a3-4252-a137-1bc5a01a9c4a.png)
