### ISSUE TITLE
Capability to setup items with ENC<1

### ISSUE THREAD

**Issue by phoenix-pnp** [sun-dragon-cult/fvtt-system-rqg#475]
### _Why:_ Is your feature request related to a problem?

As GM I'd like to correctly setup items with ENC<1

### _What:_ Describe the solution you'd like

Items in the various books are marked with the number of items needed for 1 ENC i.e. (2) for Darts or (4) for a Throwing Dagger
There should be an option to describe these correctly.

**Comment by Moonpile** [comment]
Try setting the ENC to "0.5" for an item like Darts where two equal one ENC, or "0.25" for Throwing Dagger where four equal one ENC.
