### ISSUE TITLE
Can't open actors from compendium

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#479]
### _What_: Describe the bug

Opening actors directly from a compendium logs an error and fails, see screenshot.

### _How:_ To Reproduce

1. Open an actor from for example the `Bestiary | en` compandium
2. See error in console

### Expected behavior

Should open the actor

### Screenshots

![image](https://user-images.githubusercontent.com/4853677/220849170-a27829ae-e770-42c5-a9ae-0157d556b2e5.png)

### Environment - please paste the information from foundry settings tab "support" button:

RQG 2.1.0

### Additional context

This is due to using `fromUuidSync` that does not work in compendiums. Handle that some data cannot be fetched better.

**Comment by Moonpile** [comment]
![image](https://user-images.githubusercontent.com/3959760/221093463-9c8903ac-eaae-47b6-ba7b-c5deb6c40d50.png)
