### ISSUE TITLE
Human Template include items

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#481]
### _Why:_ Is your feature request related to a problem?

The human template does not include items properly.  Use the same item include functionality to include skills, runes, hit locations, etc.

Other related considerations:

1. Remove the "species-templates" compendium and move to "bestiary"?
2. Should there be a human template for each Homeland where we override the base chance of skills (RQG p 60-63) and add the "Homeland Base Passions" (RQG p 27), and anything else that changes between homelands?
3. Does it make sense to have "Player Character" templates that have some more things on them than NPC templates?

### _What:_ Describe the solution you'd like

See above

### _Options:_ Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by Moonpile** [comment]
@wake42 thoughts on the "other considerations" section questions I raised?

**Comment by wake42** [comment]
1. Yes I think that sounds reasonable. Especially looking ahead to Foundry 11 where you will be able to organize compendiums in folders.

**Comment by wake42** [comment]
2. Not sure. Would that mean that the homeland item no longer should contain those overrides?

**Comment by wake42** [comment]
3. Yes I think that sounds reasonable, especially with the upcoming feature of compendium folders.

**Comment by Moonpile** [comment]
> Not sure. Would that mean that the homeland item no longer should contain those overrides?

Well when we go to re-work the Adventurer Wizard, that would certainly be a possibility.  Or it could be that this template is just for utility in the mean time.
