### ISSUE TITLE
Minor Compendium Errors

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#482]
### Minor Compendium Errors

This is to keep track of minor compendium errors and typos.

Scent Intruder Journal Entry has the wrong rqid.
![image](https://user-images.githubusercontent.com/3959760/221026490-1a96373c-3ca6-401e-bf57-fb2e6eca7e9f.png)

Weapon skill Kick has the name "Melee Weapon"
![image](https://user-images.githubusercontent.com/3959760/221026781-caacfe66-8cd6-4195-b233-79ed587819f2.png)

**Comment by wake42** [comment]
Hug is linked to the Kick skill
![image](https://user-images.githubusercontent.com/4853677/221044957-9a153632-e3c5-42eb-93f3-c1cca2dd34c0.png)

**Comment by wake42** [comment]
AtlatlDart & AtlatlJavelin is missing a skill
![image](https://user-images.githubusercontent.com/4853677/221045303-14558e19-a811-40f5-93e8-e252693f59fe.png)
![image](https://user-images.githubusercontent.com/4853677/221045468-80e36bbd-227f-44bd-97f9-ed42a21c3602.png)

**Comment by wake42** [comment]
Sling stones are equipped by default, should be carried
![image](https://user-images.githubusercontent.com/4853677/221046394-d7c1096e-7190-4b72-95fa-187b93c052ea.png)
