### ISSUE TITLE
Bestiary import errors/warnings: Actor hit points value null is missing

### ISSUE THREAD

**Issue by phoenix-pnp** [sun-dragon-cult/fvtt-system-rqg#483]
### _What_: Describe the bug

For spirits, ghosts and elemental which do not have CON the import complains "Actor hit points value null is missing in actor <type>"

### _How:_ To Reproduce

Import bestiary compendium pack.

### Expected behavior

No warning, as this is no error

### Screenshots
![image](https://user-images.githubusercontent.com/18349726/221029908-3b0dddc9-c35e-41b6-9a70-b65af8780a54.png)

**Comment by Moonpile** [comment]
![image](https://user-images.githubusercontent.com/3959760/221093284-c563a56f-0d51-411b-90b5-5e2768027fe1.png)
