### ISSUE TITLE
Cannot Edit Rune on Actor

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#485]
### _How:_ To Reproduce

1. Go to the Runes tab on an Actor
2. Right click a Rune and choose "Edit Rune"
3. Nothing happens except error in console

### Expected behavior

Expected Rune Item sheet to be displayed

### Screenshots

foundry.js:747 Error: An error occurred while rendering $t 434. Syntax error, unrecognized expression: #$t-Actor-C7lzPdQjQcQLtWin-Item-OxYAAYY4OMvJo1Ox
[Detected 1 package: system:rqg]
    at se.error (jquery.min.js:2:13639)
    at se.tokenize (jquery.min.js:2:21650)
    at se.select (jquery.min.js:2:22477)
    at Function.se [as find] (jquery.min.js:2:7116)
    at S.fn.init.find (jquery.min.js:2:25047)
    at new S.fn.init (jquery.min.js:2:25536)
    at S (jquery.min.js:2:1051)
    at get element [as element] (foundry.js:4983:12)
    at $t._render (foundry.js:5818:22)
    at $t.render (foundry.js:5067:10)
    at $t.render (foundry.js:6394:18)
    at Object.callback (rune-context-menu.js:94:18)
    at #onClickItem (foundry.js:56177:11)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5069
Promise.then (async)
render @ foundry.js:5067
render @ foundry.js:6394
callback @ rune-context-menu.js:94
#onClickItem @ foundry.js:56177
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

### Environment - please paste the information from foundry settings tab "support" button:

Core Version: 10.291

System: rqg 2.1.0 (Sun Dragon Cult, Wake, Moonpile) 

### Additional context

n/a

**Comment by Moonpile** [comment]
In the rune-context-menu, the item.sheet.form is null:

![image](https://user-images.githubusercontent.com/3959760/221067033-f8a370d4-c809-4026-b1d8-807f4de1f3de.png)

By comparison, in the skill-context-menu the item.sheet.form has a value:

![image](https://user-images.githubusercontent.com/3959760/221067172-bec4caae-7bef-4be2-89ca-3d4f1305e4b0.png)

**Comment by Moonpile** [comment]
@wake42 I can't figure out why that form is null at that point (assuming that's the problem).  I figured it might have something to do with the sheet registration but that looks ok. Any ideas?

**Comment by wake42** [comment]
I tried this but I can't reproduce it. Could it be something specific to this actor/rune ?

**Comment by Moonpile** [comment]
I can't open any Runes, even from the world or compendium. I can create a new Rune in the world but then I can't edit it because the sheet doesn't render.

I originally reported it from my play environment which is 2.1.0, and I have the same problem from building the current master.

**Comment by Moonpile** [comment]
I've tried deleting dist, rebuilding master, creating an entirely new world, and I'm still having this problem.

**Comment by Moonpile** [comment]
I'm on Foundry Version 10 - Build 291

**Comment by wake42** [comment]
I created a new world, imported the bestiary Dwarf, rightclicked the rune and it opened.
I'm on Chrome
![image](https://user-images.githubusercontent.com/4853677/221280272-63201df7-ce7d-426a-859c-f5236ee4ba9b.png)


![image](https://user-images.githubusercontent.com/4853677/221279998-17d607a4-d139-43e6-8c7d-f0e4ef18db24.png)


Foundry Virtual Tabletop: Version 10, 10.291
Game System: rqg, 2.1.0
Active Modules: 0
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
GPU: ANGLE (Intel Inc., Intel(R) UHD Graphics 630, OpenGL 4.1)
Max Texture Size: 16384

No viewed scene

Actors: 1 | Items: 0 | Journal: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 51 | Chat Messages: 2

**Comment by wake42** [comment]
I can reproduce it now - it works in my unminified build - but fails in the released build 
![image](https://user-images.githubusercontent.com/4853677/221282979-f5498481-69a5-4ead-b4c3-d166d6c76ef3.png)
I'll have a look - I've seen this before so maybe I can find the place that fails...
