### ISSUE TITLE
Experience Checks should show anywhere a skill is displayed

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#487]
### _How:_ To Reproduce

1. Add a weapon.
2. Equip it
3. Give it's skill an experience check
4. Look at the combat tab and see the "checked" glow
5. Look at the Gear tab and you will not see the "checked" glow.

### Expected behavior

Anywhere a skill percentage is shown, it should glow if the skill is checked.

### Screenshots

Gear Tab:
![image](https://user-images.githubusercontent.com/3959760/221093043-a2aa5416-f39d-47f2-8eff-8a8711e2ee89.png)

Combat Tab:
![image](https://user-images.githubusercontent.com/3959760/221093029-2ae3a002-a033-450d-9e13-564bfc6ee8db.png)

### Environment - please paste the information from foundry settings tab "support" button:

2.1.0

### Additional context

n/a

**Comment by Moonpile** [comment]
@wake42 I don't think this is critical to 2.1.1 and can wait until 2.2.0.

**Comment by wake42** [comment]
It could but the solution is also a one liner I think.
