### ISSUE TITLE
Sling Should have Half Damage Bonus

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#497]
### _What_: Describe the bug

The Sling should have half Damage Bonus

```
Can you clarify which Thrown & Missile Weapons receive half Damage Bonus?

Bows & Crossbows do not receive any Damage Bonus
Javelins, Spears get half Damage Bonus
Thrown Weapons get half Damage Bonus
Slings, get half Damage Bonus
```
https://wellofdaliath.chaosium.com/home/catalogue/publishers/chaosium/runequest-roleplaying-in-glorantha/cha4028-runequest-roleplaying-in-glorantha-qa-by-chapter/cha4028-runequest-roleplaying-in-glorantha-chapter-08-combat-qa-part-2/#ib-toc-anchor-26

### _How:_ To Reproduce

n/a

### Expected behavior

There should be a way to define a Missile Weapon as a Projectile Weapon that also gets Half Damage Bonus.

Would tags be a better way to do this?  Like add the tag "Projectile Weapon" and the tag "Half Damage Bonus"?  

Tags might include:

- Thrown Weapon
- Projectile Weapon
- Projectile (ie ammo)
- Half Damage Bonus
- No Damage Bonus
- Full Damage Bonus (Maybe just in case a GM wants to make a magic or special weapon?)
- Ranged (what is the Ranged Weapon?  Only Pole Lasso has this checked, so I guess it's more of a "reach weapon"?)

### Screenshots

![image](https://user-images.githubusercontent.com/3959760/221721289-8d030a75-feb1-408d-96ce-c1801d6aecdc.png)

### Environment - please paste the information from foundry settings tab "support" button:

[...]

### Related issue
- [ ] #106

**Comment by wake42** [comment]
Solution is the same as in #106 so fix the problem there
