### ISSUE TITLE
Human Templates should not have Natural Armor

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#502]
### _What_: Describe the bug

The Human (Sartarite) template in the Bestiary Compendium has Natural Armor when it should not.  Double check all the templates and correct.

### _How:_ To Reproduce

1. Go to the Bestiary compendium and look at "Human (Sartarite)".

### Expected behavior

Templates should have correct values for Natural AP

### Screenshots

![image](https://user-images.githubusercontent.com/3959760/229311777-fdd97f3a-6a5c-49b7-93cf-621f3375d704.png)

### Environment - please paste the information from foundry settings tab "support" button:

2.1.1

### Additional context

n/a

**Comment by wake42** [comment]
Also remove natural armor from "Human (Base)" template and increase the encumbrance factor to 2 for the horse

**Comment by wake42** [comment]
Closed by: 3918306829228a84981fb60ab92c935740e17977
