### ISSUE TITLE
Ranged Weapons Should Show Range

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#504]
### _Why:_ Is your feature request related to a problem?

Ranged weapons should show their range on the "Weapons & Shields" grid on the Gear tab, and in the Combat tab.

### _What:_ Describe the solution you'd like

Show the range on on the "Weapons & Shields" grid on the Gear tab, and in the Combat tab.

### Additional context

![image](https://user-images.githubusercontent.com/3959760/229311988-fa4fefdc-2e4f-47af-a02e-43174a23d499.png)

![image](https://user-images.githubusercontent.com/3959760/229311995-6efb5090-f82d-483d-abb8-4492a3c664de.png)

**Comment by wake42** [comment]
implemented in commit 51d100396ad4de17f3e27c6c2602e510b88dddaf (case #510 )
