### ISSUE TITLE
Reset Initiative Should Remove Duplicated Combatants

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#509]
### _Why:_ Is your feature request related to a problem?

As a GM, if there are duplicated combatants in the Combat Tracker, resetting the initiative should remove the duplicates for convenience.  Yes, this might mean re-duplicating the combatant, but they might not be doing something that lets them act twice in a round the next round.

### _What:_ Describe the solution you'd like

When you click the reset initiative button it should remove duplicated combatants from the Combat Tracker.

### _Options:_ Describe alternatives you've considered

Have to delete them by hand.  Can confuse similarly named actors.

### Additional context

n/a

**Comment by wake42** [comment]
Also rename the button to "Reset SR".
And the two buttons for "Roll All" & "Roll NPCs" should be removed.



![Image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/4853677/a8e46131-a2fe-41f9-9670-0252c54b9daa)
