### ISSUE TITLE
Double Click Rune Spell blanks Magic Points and Rune Points

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#511]
### _What_: Describe the bug

When double clicking a Rune Spell yields a result that causes spending Rune Points or Magic Points, the Actor's Rune Points and Magic Points get blanked, probably because there was never a chance to enter values on the "Card" that never was displayed. 

### _How:_ To Reproduce

1. Go to Rune Magic
2. Make sure you have Rune Points and Magic Points
3. Double Click a spell until you get a result other than Critical
4. Note that Magic Points and Rune Points are blanked

### Expected behavior

Either spend the minimum Rune Points and/or Magic Points 

OR

Just don't allow Double-Clicking spells.  There's almost always something you need to choose and you should probably always have to use the card to choose that stuff.

### Screenshots

Before
![image](https://user-images.githubusercontent.com/3959760/230528789-98f23606-0e8c-417a-9ec1-915c92a4b64d.png)

After

![image](https://user-images.githubusercontent.com/3959760/230528825-319d8834-cffb-4c92-8316-0dfff05e8c24.png)

### Environment - please paste the information from foundry settings tab "support" button:

RQG 2.1.1
Foundry 10.291

### Additional context

n/a

**Comment by wake42** [comment]
closed by 75dfd0efa5cc2d0aac07b44af3098f08d0863c6e
