### ISSUE TITLE
Improve UX of MOV for players

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#516]
### _Why:_ Is your feature request related to a problem?

The panel for displaying MOV and how much equipped weight a character has can be hard to understand. Try to simplify it.

### _What:_ Describe the solution you'd like

Simplify the panel to something like this, and add a tooltip that shows detailed information.
![image](https://user-images.githubusercontent.com/4853677/230747120-9deb005f-c7e3-4022-83e3-bb971fad6939.png)

The tooltip should show something along these lines:
```
Equipped (combat ready) MOV is 8 and the total equipped ENC is 7 out of 10 maximum.
Carried (traveling) MOV is 7 and the total carried ENC is 12 out of 10 maximum. MOV is reduced because of overweight.

Move 8 Units of Movement = 24 meters" or "Move 3 Units of Movement = 4.5 meters
```
Think about if the max encumbrance values should be shown on the gear tab, since they after this change only are visible as a tooltip.

### Additional context
For reference the player view looks like this now
![image](https://user-images.githubusercontent.com/4853677/230747139-ed96acca-30b3-4eaa-89e8-bdc6e9ece754.png)

**Comment by Moonpile** [comment]
> Think about if the max encumbrance values should be shown on the gear tab, since they after this change only are visible as a tooltip.

That's a great idea!  Just the MOV values should be on the header.  The breakdown of Current ENC/Max ENC should be on the Gear tab.  Makes total sense.
