### ISSUE TITLE
 Make AP/HP presentation consistent with paper character sheet

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#517]
### _Why:_ Is your feature request related to a problem?

As a GM or player, I want the Armor Point and Hit Point presentation to be more consistent with the way they are presented in RQ books and in the character sheet.

### _What:_ Describe the solution you'd like

At a minimum, move the AP column to before the HP column.  The slash notation in the books means "AP/HP", and we have it meaning "Current HP/Max HP" and this could confuse people used to the long-standing paper presentation of this information.

A better solution might be to have an "AP/Max HP" column and another column for current HP.

| | Hit Location| AP/Max HP | Current HP| Wounds |
|--|--|--|--|--|
|19 - 20 | Head | 3/5 | 2 | 3 [button] |

Also, @wake42 I know we've discussed this at least once but the books all show the hit locations with head at the bottom because the higher dice results are at  the bottom.  We may want to consider that or even just have a button to flip the sorting or maybe a system setting.

### _Options:_ Describe alternatives you've considered

n/a

### Additional context

What we have currently:

[Add any other context or screenshots about the feature request here.](https://media.discordapp.net/attachments/1093285480927338638/1094327877828366479/Foundry_Hit_Locations.png)

An example of the presentation in a book:

![image](https://user-images.githubusercontent.com/3959760/230789887-4d01ea26-504d-4943-89a6-266878f772b8.png)

The official Character sheet:

![image](https://user-images.githubusercontent.com/3959760/230789907-125ca978-5c16-4b7e-b70d-ac60982a2709.png)

**Comment by wake42** [comment]
I'll adjust this. And if it's deemed to be important to have the hitlocations upside down then I'll add a setting so you can choose how you want it. Personally I can't see why you would want the head at the bottom 🙂 And the paper character sheets have the head at the top.

**Comment by Moonpile** [comment]
A button to flip the sorting by the dice ranges makes everyone happy.
