### ISSUE TITLE
Add Rune Images in White

### ISSUE THREAD

**Issue by Moonpile** [sun-dragon-cult/fvtt-system-rqg#519]
### _Why:_ Is your feature request related to a problem?

As a GM, I want to be able to use Rune Images from "systems/rqg/assets/images/runes" as tiles on a scene or as tokens or other images, and I would like to have them available in a variety of colors.  If we provide the runes in white, I can use the tint feature to make them any color I want.

### _What:_ Describe the solution you'd like

Render the runes in a variety of colors and have them in folders like "systems/rqg/assets/images/runes/white" or "systems/rqg/assets/images/runes/blue".  

And for Extra Credit, there's apparently some way to register a directory with Moulinette so that it's automatically hooked up.  Apparently Baileywiki modules do this with their images.  We might want to see if it's worth doing that as well.

### _Options:_ Describe alternatives you've considered

This is entirely a "nice to have".

### Additional context

In Moulinette you can configure a source and point it to any folder full of images.  This is handy for the runes in particular but might be useful for other images we provide with the system.

![image](https://user-images.githubusercontent.com/3959760/231016771-59d9dc62-55fb-47bf-82d8-ce0c30d4e364.png)

Then you can view the images in that directory in Moulinette and drag them out as tiles or tokens.

![image](https://user-images.githubusercontent.com/3959760/231016879-0680bb4c-d141-4c92-bfef-d96a206293fd.png)

Here I've placed a rune using a macro from Baileywiki to give it a drop shadow

![image](https://user-images.githubusercontent.com/3959760/231018657-2b581c97-2534-4ca7-b4ac-cfe440270f63.png)

And here's a white Air Rune with tint applied.

![image](https://user-images.githubusercontent.com/3959760/231034165-f54a675c-d444-4db9-aee1-421e77ac7f0d.png)

**Comment by wake42** [comment]
I haven't used moulinette, but from what I understand the tint is a macro, wouldn't it be possible to do a "invert color" in a macro so you don't have to duplicate the actual images? In other words create a "tintBlack" macro that first inverts, then tints.

**Comment by Moonpile** [comment]
And I highly recommend Moulinette.  I think it's going to become one of those "must have" mods, and one that warrants any (optional) integration with it that we can think of, like registering our images directory as a "pack" with it automatically.

**Comment by wake42** [comment]
Actually I'm starting to think that the default color for rune item images should be white, and the black one is a special case... If so then maybe we don't need this case. Instead I could modify the svgs so that I can color them black just in the actorSheet (using svg `fill: currentColor;`) to make it possible to style them to blend into the background (as they are now).
