### ISSUE TITLE
Unable to edit characteristics and runes when logged as a player

### ISSUE THREAD

**Issue by dyvim** [sun-dragon-cult/fvtt-system-rqg#560]
Add a player edit mode that makes it possible for players to edit characteristic values, rune chances, skill chances & background info. 

One way of doing this could be to add a "GM's tools" menu similar to the "CoC Keeper's tools" with a "Character creation mode" - that would affect all actors. An alternative could be to add a setting on the actor sheet that would affect the each actor individually.

---

### _How:_ To Reproduce

Log as a player
Go in the Runes tab
Right clic on a Rune
No Edit Rune option in the menu is shown
Right clic on a Characteristic
No Edit characteristic option in the menu is shown

### Expected behavior

The menu should propose Edit Rune or Edit Characteristic options

### Screenshots

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/8790994/fc317802-9692-412f-b0ed-6ca9e806557f)
![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/8790994/645b0203-682b-46f0-88d1-65bee5af7ee3)

### Environment - please paste the information from foundry settings tab "support" button:

Foundry Virtual Tabletop: Version 10, 10.291
Game System: rqg, 2.2.0
Active Modules: 26
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
GPU: ANGLE (Intel, Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 3451 x 4573 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 3 | Tokens: 0

Actors: 19 | Items: 20 | Journal: 21 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 58 | Chat Messages: 86

### Additional context

N/A

**Comment by wake42** [comment]
The idea is that some things should not be editable by the player, while everything should be editable by the GM. Some things like the setup of a hitlocation or the connection of one rune to another rune does not make sense to let players edit. Originally most things we GM only edit, but gradually more and more things can be edited by players also, and there is definitely an argument for letting the player edit more things if it makes sense. 

What is the usecase for letting players edit their characteristics value and rune percentage? I would imagine these are set when the character is created and rarely changed after that (other than by improving them, and that is handled by the improvement context menu). But I'm open to changing my mind if there is a good usecase for it!

**Comment by dyvim** [comment]
Hello.
Thanks for the explanation.

From my point of view, a setting for the GM in the configuration tab to
allow players to edit the sheets (setting that you can toggle ON/OFF) could
be useful.

The use case is that at character creation, lots of GM will let their
players fill their sheets themselves to spare time. And you're right after
character creation, the players normally shouldn't be able to edit their
skills, characteristics , passion and runes. All modification after
creation  is supposed to be done by experience rolls.
There's AFAIK only the possibility to gain a new passion after creation.

BRgds
Thomas Coquery



Le dim. 25 juin 2023 à 19:54, Åke Wivänge ***@***.***> a
écrit :

**Comment by wake42** [comment]
There has been an idea of more formalized /guided steps in a character creator, but looking at it again I can see the value of having a player edit mode where more things are editable (specifically characteristic values, rune chances, skill chances & background info). I will change this issue to be a feature request and add it to the backlog.

**Comment by Moonpile** [comment]
Sub Tasks: 
* #632

**Comment by wake42** [comment]
closed by #633
