### ISSUE TITLE
Find Rqid from Actor Compendiums makes Chrome run out of memory

### ISSUE THREAD

**Issue by Sinickal** [sun-dragon-cult/fvtt-system-rqg#565]
### _What_: Describe the bug

I've just moved from RQG 2.2.0 to 2.2.2 and when I load my RuneQuest world the update starts a process; Find Rqids from Actor Compendiums. Initially was out of 6500, removing ALL modules now at 'of 4900.' But process terminates between 10-15%, I believe from running out of memory.

Error code in browser: Error code: Out of Memory

### _How:_ To Reproduce

Steps to reproduce the behaviour:

Each time I log into my RQG world via Forge.

Using Google Chrome.

Have deleted browser cookies, data etc and restarted PC.

### Expected behavior

Was expecting the update from 2.2.0 to 2.2.2 to just run smoothly, not sure what's not happening!

### Screenshots

![Forge RQG 2 2 2 problem](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/134496212/42bdbdbc-c94f-4365-b740-e555759fb5df)

### Environment - please paste the information from foundry settings tab "support" button:

I am running Foundry via Forge. The RQG 2.2.0 was running ok, with some Rqids problems, mainly skill related. Was hoping 2.2.2 would resolve these.

**Comment by Sinickal** [comment]
Using Forge, with Foundry v10, build 303 (base.)

**Comment by wake42** [comment]
Thanks for the bug-report!
I'm aware of the problem for worlds with actor compendiums and am looking into what can be done.

Until I've found a solution the best way is probably to rollback to version 2.2.0 that didn't try to find items embedded in actor compendiums.

**Comment by wake42** [comment]
solved in b649e8b448b638ba9fadb3b23674d638d5183b1e

**Comment by Sinickal** [comment]
Morning.

 

Upgraded to RQG 2.2.3 this morning via Forge and restarted World; ripped through Actor Compendium checks and successfully migrated to version 2.2.3 😊

 

Thank you. Will do further checks through the day.

 

Don.
