### ISSUE TITLE
error when using missile - remaining usage of skillId instead of rqid

### ISSUE THREAD

**Issue by Sinickal** [sun-dragon-cult/fvtt-system-rqg#567]
Foundry v11 304
RQG 2.2.3 active modules 16
New Actor set up (we are moving all previous 2.2.0 actors to new Actors to try and avoid old issues.)

Actor using Human (Sartarite) from Bestiary compendium
Added skills for Sling and Self Bow
Added Sling and Self Bow; sling stones equipped and arrows equipped.

Problem; when we use/fire Sling or Self Bow, the 'shoot' dialog box seen and ammo reduces by onw, but following error seen/encountered

![RQG error - ranged weapon](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/134496212/6fa14580-a23e-42f5-95a3-f1c5e3aa42b9)

First question, have I missed or done something wrong? Is there anything I should check to confirm if error/bug?

**Comment by Sinickal** [comment]
Just did the same with a Javelin ;)

**Comment by wake42** [comment]
I tried to reproduce this way but couldn't:
1. import `Human (Sartarite)`
2. drag sling stones & sling to imported actor
3. link sling to use sling stones as projectile
4. equip both sling and sling stones
5. use the sling

Could you please look in the console (F12) and post where it fails (there are multiple places that check exists).

Also could you post a screenshot of the sling item sheet usage tab (right click on the weapon, choose "Edit Weapon", select the "Usage" tab and hover over the Skill link, see my screenshot)
![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/4853677/6eede403-6704-4c73-a232-c85c7affca03)

**Comment by Sinickal** [comment]
Have re-tested.

World 1: was initially setup as RQG 2.2.0 (or 2.2.1) and upgraded to 2.2.2, and started to see issues with rqid's, especially Missile weapons. Have upgraded to 2.2.3 and migration was successful, but still encountered Missile issues as noted above. Tried with old Actors and setting up new Actors, but as of this am, still same issue as above. Checks the Usage tab etc, but no change.

World 2: Set up a new world and new install of RQG 2.2.3. Exported 'new Actor' from World 1 and imported into World 2, but same issue found (JSON attached.). So use Bestiary for new2 Actor (Sartorite) human, set sling skill and gear with stones etc, used Sling and ALL OK :)

I'm thinking this is not a Bug per-se, rather an issue in World 1 that may not be resolvable! Will talk to my players and see if we want to migrate over to World 2 to resolve.

**Comment by Sinickal** [comment]
Exported JSON from World 1 below;
