### ISSUE TITLE
ENC penalties are not applied to weapon skills

### ISSUE THREAD

**Issue by Lockbox313** [sun-dragon-cult/fvtt-system-rqg#601]
### _Why:_ Is your feature request related to a problem?

ENC penalties are not being applied to weapon skills

### _What:_ Describe the solution you'd like
As per pg 150 of the core book ENC penalties should be applied to weapon skills

**Comment by wake42** [comment]
It seems like they are applied when I test. In the screenshot I overloaded a character severely and the category bonuses are updated. Do you see some other behaviour?

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/4853677/cd5fe95a-986f-4cc6-b291-c2c67a50c348)

**Comment by Lockbox313** [comment]
hmm I just updated to 2.2.6 and tried it again and it is applying them so it must have been 2.2.5 issue.
