### ISSUE TITLE
Improve actorSheet health / hitLocation display 

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#605]
### _Why:_ Is your feature request related to a problem?

Improve display of hitlocation table and display a man rune similar to the paper character sheet for humanoids.

**Comment by Lockbox313** [comment]
Thank you for creating the option

**Comment by wake42** [comment]
oh sorry, maybe I wasn't quite clear - I didn't add an option to have the old style of showing "actor health state"  - but I redesigned it completely instead. I tend to be conservative about adding options...
