### ISSUE TITLE
Location tags

### ISSUE THREAD

**Issue by HawkofMay** [sun-dragon-cult/fvtt-system-rqg#612]
Why: If you use the same location tag on more than one item in your inventory and then you change the status (carried, equipped, not carried) on one of them, the status changes on all of them.

What: Could you fix it so only the item you want to change the status on changes not all of them.

Options: The easiest fix is not to use the tags, but I like being able to open a player's page to see where things are kept.

**Comment by wake42** [comment]
There has already been a case for that: #93, but I decided against doing it. The idea with "location" is that you can put stuff inside other stuff, and while there is a view of items where they are organised to display that structure (see screenshot in the linked case), the default view is to group items by category (gear, currency, armor, etc.). If I remove the location when an item's equipped status changes, then other items inside that item will also change in a way that is not obvious by just looking at the default gear view.

Removing an item from a bag is equivalent to clearing the location, and after that you can change the equipped status without affecting anything else (as you've already figured out). Personally I use the "everything is affected" to quickly equip a whole suit of armor for example. 

Any ideas for how the location system could be improved are welcome. I've toyed with the idea of adding an icon to the gear that is also a container. In the "by location" view there is a "folder" icon for things that actually contain thing, but you can't see which items are capable of containing other items (they show up in the location dropdown though).

I'm closing this case for now, but feel free to reopen it!
