### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#62]
How should the documentation of the system be structured? Wiki / Journals / Foundry Tours / something else?

Make sure to explain both for GMs new to Foundry and GMs that already are used to Foundry.

**Comment by Moonpile** [comment]
“Background” Item?
There are a lot of things in common between Homeland (and Tribe and Clan), Occupation, “Family History Event”, and Cult, in that they all do one or more of the following:
Give a Bonus to a Characteristic
Give Skills
Give Runes
Give Passions
Give Equipment 
Give Rune Magic Spells
Give Spirit Magic Spells
Prohibit Spirit Magic Spells
Give Sorcery Techniques
Give Sorcery Spells
Give Sorcery Rune Mastery
Give a bonus to Spirit Combat Damage
Give a Standard of Living
Give a Base Income
Give a Ransom
Give Reputation
Give Scars
Suggest & Link to Cults
Suggest & Link to Occupations
Designate Skills as Income Skills
Make Skills available for training
Link to a description of themselves
Provide an entry in the Family Chronicle
Provide some instructions?
“Give” here means either a Skill, Rune, or Passion and a bonus (which could be +0%) , or a choice among two or more such.

**Comment by Moonpile** [comment]
See more notes related to character creation at: https://docs.google.com/document/d/1sYwV-BeVclY-nSTwrSCWrkNxlefhDNSt-zGNkluEU3A/edit?usp=sharing
