### ISSUE TITLE
How do I get a custom weapon skill to link to a custom weapon?

### ISSUE THREAD

**Issue by jjhritz** [sun-dragon-cult/fvtt-system-rqg#623]
Foundry: 11.308 Stable
rqg: 3.0.0

I'm working on setting up the scorpion men and krarshtkid from the starter box for a game; both have natural weapons that aren't included in the compendium (Stinger for the Scorpion men, and Tongue, Spit, and Swallow for the krarshtkid).  

Using the natural weapons from the compendium as a model, I've created a skill item called Tongue, given it the Melee Weapon description entry, and set its category to Melee Weapons.

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/17412506/427a80e8-e3a9-4c81-8552-c7a04ac4620c)
```JSON
{
  "folder": "Y1p9tQybJ5T09tod",
  "name": "Tongue",
  "type": "skill",
  "img": "systems/rqg/assets/images/items/skill.svg",
  "system": {
    "category": "meleeWeapons",
    "skillName": "Tongue",
    "specialization": "",
    "baseChance": 25,
    "gainedChance": 0,
    "canGetExperience": true,
    "hasExperience": false,
    "runes": [],
    "namePrefix": "Tongue",
    "descriptionRqidLink": {
      "rqid": "je..melee-weapon",
      "name": "Melee Weapon"
    }
  },
  "effects": [],
  "flags": {
    "rqg": {
      "documentRqidFlags": {
        "lang": "en",
        "priority": 999999,
        "id": ""
      }
    },
    "core": {},
    "exportSource": {
      "world": "bronze-age-comstar",
      "system": "rqg",
      "coreVersion": "11.308",
      "systemVersion": "3.0.0"
    }
  },
  "_stats": {
    "systemId": "rqg",
    "systemVersion": "3.0.0",
    "coreVersion": "11.308",
    "createdTime": 1694830913107,
    "modifiedTime": 1694831622371,
    "lastModifiedBy": "pbbyR5aNWcRZt3Aa"
  }
}
```
Then I create a weapon item called Tongue, marking it as a natural weapon and set the hit point location to "body" (matching the name of the hit location on the krarshtkid) on the Weapon tab.  On the Usage tab, I give it a one-handed combat maneuver to populate that part of the interface, set Damage Type to Special, then try to drag the Tongue skill into the box as the info button directs.  The linked skill does not appear in the box, and trying to add the weapon to an actor anyway doesn't work around the issue.
![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/17412506/fd2e4d8e-3abd-4456-a545-77d2a4f6a4ef)

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/17412506/49b7e57b-6cea-46da-9307-c9c354fb3717)
```JSON
{
  "folder": "Y1p9tQybJ5T09tod",
  "name": "Tongue",
  "type": "skill",
  "img": "systems/rqg/assets/images/items/skill.svg",
  "system": {
    "category": "meleeWeapons",
    "skillName": "Tongue",
    "specialization": "",
    "baseChance": 25,
    "gainedChance": 0,
    "canGetExperience": true,
    "hasExperience": false,
    "runes": [],
    "namePrefix": "Tongue",
    "descriptionRqidLink": {
      "rqid": "je..melee-weapon",
      "name": "Melee Weapon"
    }
  },
  "effects": [],
  "flags": {
    "rqg": {
      "documentRqidFlags": {
        "lang": "en",
        "priority": 999999,
        "id": ""
      }
    },
    "core": {},
    "exportSource": {
      "world": "bronze-age-comstar",
      "system": "rqg",
      "coreVersion": "11.308",
      "systemVersion": "3.0.0"
    }
  },
  "_stats": {
    "systemId": "rqg",
    "systemVersion": "3.0.0",
    "coreVersion": "11.308",
    "createdTime": 1694830913107,
    "modifiedTime": 1694831622371,
    "lastModifiedBy": "pbbyR5aNWcRZt3Aa"
  }
}
```

These weapons and skills are not stored in a compendium, they're in the item tab of the outliner.  I feel like I'm missing a step here somewhere but I can't tell where.

**Comment by Moonpile** [comment]
@jjhritz did you give the Tongue skill an rqid?  Open the tongue skill and click on the fingerprint icon in its title bar.  Then click on the magic want icon next to the "RuneQuest System ID (Rqid)" field and it will generate one for you.

![image](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/3959760/fde9ffd1-fb94-4496-aee5-d8546f329cb2)

**Comment by wake42** [comment]
@jjhritz Did this solve it for you?

**Comment by jjhritz** [comment]
Yes, it did.  I missed that part (and the response.  Busy days). Thank you!
