### ISSUE TITLE
Impossible to open character sheets

### ISSUE THREAD

**Issue by Aliath94** [sun-dragon-cult/fvtt-system-rqg#627]
Hey
Unable to open the character sheets since the last maj, but the one created for the test.
Ver. [v3.1.0]
Thx

**Comment by wake42** [comment]
I also just realised that there is a bug with the released version. I managed to work around it by opening the character as a GM, and reloading the page. But I will try to find the root cause.

**Comment by Aliath94** [comment]
thx
