### ISSUE TITLE
Modify POW gain roll for runepriests

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#649]
### _Why:_ Is your feature request related to a problem?

If you are a runepriest or god talker (and possibly runelord?) you get should get a 20% bonus to the POW gain roll. See RQG p276

### _What:_ Describe the solution you'd like

If the actor has a subcult with rank of `GodTalker`, `RunePriest` , `ChiefPriest`  or `HighPriest`(verify if `RuneLord` also should get this) add a 20% bonus to the POW gain roll.

**Comment by The-Axel** [comment]
RuneLords do not get a bonus to their POW gain roll.

**Comment by wake42** [comment]
This was actually implemented before but became a bug during a previous refactoring.
Now `God Talker`, `Rune Priest`, `Cheif Priest` & `High Priest`get 20% bonus to the POW roll
