### ISSUE TITLE
Combat automation

### ISSUE THREAD

**Issue by CharlesRampant** [sun-dragon-cult/fvtt-system-rqg#660]
### _Why:_ Is your feature request related to a problem?

The current version does not have any automation in combat, which requires much referencing of the Combat Results table in rulebook. This is not ideal, and leaves a lot of room for speeding up combat through the system doing the necessary steps automatically.

### _What:_ Describe the solution you'd like

When an attack action (and spell, etc.?) is clicked and another token is being targetted, the system would prompt the target to select a weapon skill or dodge to resist with. It would then wait for both parties to select required options (Cut, Parry, etc.) before rolling all the dice simultaneously. It would ideally roll the hit location, damage, weapon damage and such, and then just present the final outcome.

Example:

> _Attacker - special success [15% out of 90%], defender normal success [40% out of 50%]._
> 
> _Result:_
> _Attacker rolls special damage. Defender’s parrying weapon takes damage over its HP, with same amount of damage going to adjacent hit location._
> 
> _Damage:_
> _Damage is [20]._
> 
> _[Vasana]'s [Broadsword] takes 1 HP for a parry that goes over its HP total, plus an additional [8] HP for the damage over its HP total due to the special success. Vasana's Broadsword has [3] HP left._
> 
> _Vasana takes 8 HP due to the parry being successful. This goes to location 3, Right Leg, which takes [2] HP of damage after armour._

### _Options:_ Describe alternatives you've considered

The above is just an idea, but ultimately I think that the system should not require the players to manually determine success / failure in an opposed combat interaction. It should be able to remove that element, which will dramatically speed up play especially for newer groups.

### Additional context

The CoC 7e system has something similar.

**Comment by wake42** [comment]
I totally agree and there is a "placeholder case" #116 planned. The reason it's not planned for the coming release is that I wanted to get as many "breaking" changes that change the data models done as early as possible.

I'll close this case but I'll have a look at this when I get to #116.
