### ISSUE TITLE
Provide an option to hide Hero Points

### ISSUE THREAD

**Issue by jmickey8080** [sun-dragon-cult/fvtt-system-rqg#661]
### _Why:_ Is your feature request related to a problem?

Hero Points appear to be part of a proposed ruleset for HeroQuesting and are not part of the official published rules at this time (please correct me if I'm wrong). Because they appear on the main actor sheet when owned by a player, players who do not follow online discussions on proposed rules become confused that there is some game mechanic they are missing (or I am keeping from them).

As such, they should be treated as house rules and should be opt-in only. We've been waiting for 40 years for HeroQuesting rules, I'm taking any proposed rules with a grain of salt, no matter how close they may seem to be to being published. That ship has sailed for me a long time ago, and even if such rules are published I would likely not use them anyways. Therefore, a way to hide them would still be useful for GMs.

Finally, refer to the rule book (CHA4028) page 7, which explicitly states "...there are no hero points [to bail your adventurers out]..."

### _What:_ Describe the solution you'd like

Provide a setting to hide Hero Points or remove them completely from the system until such time the rules are published, and then provide a setting to hide them.

### _Options:_ Describe alternatives you've considered

It appears using the "Is Creature?" checkbox hides hero points, but it also disables skill category modifiers, so it is not a suitable solution.

**Comment by wake42** [comment]
I was actually about to write this case so thanks for doing it for me :-) There will be an opt-in setting in the next release.

**Comment by jmickey8080** [comment]
That would be great! Also, I am enjoying the work you and the other contributors have done so far, it is truly impressive, thank you.
