### ISSUE TITLE
Loosen duplicate embedded item check

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#672]
Adding two javelins currently require you to rename them so they have unique names. Also splitting your currency into multiple piles requires that you rename your `Lunars` items  to have unique names. Unique Physical Items do not have quantity (locked to 1) but it should still be possible to have more of them as separate items.

There is a check that all items (except RuneMagic) has to be unique <type+name> (see `rqgItem.isDuplicateItem`). RuneMagic was removed from the check since you must be able to have the same spell learned from multiple cults. The physical items (gear, armor & weapon) should also be excluded from this uniqueness check.

**Comment by Moonpile** [comment]
I know we've discussed this many times.  I'd be ok with the side-effect of all 7 broadswords lose hit points.  Maybe just have a warning pop up if you equip something and there's a quantity other than 1.
