### ISSUE TITLE
Selecting Ammo on Combat Section of Character Sheet Initiates a Dice Roll Card

### ISSUE THREAD

**Issue by claycle** [sun-dragon-cult/fvtt-system-rqg#701]
### Selecting Ammo Initiates a Dice Rol

When attempting to select the ammunition for a ranged weapon (eg, using Sling Stones with a Sling), there is a side-effect that a combat roll card will be generated in the chat stream. This behavior is not desired and the card must be ignored or deleted.

### Steps to Reproduce

1. Drop and equip a ranged weapon on the character sheet (eg, Sling)
2. Drop and equip ammunition for the weapon on the character sheet (eg, Sling Stones)
3. In the combat section of the character sheet, change the ammunition type for the Sling from "None" to "Sling Stones".

### Expected behavior

When changing the ammunition for a weapon, propagation of the click needs to stop at the ammunition selector and not continue to the encompassing weapon.

### Screenshots

Equipped weapon and ammo, default setting (no ammo):
<img width="789" alt="Screenshot 2024-03-19 at 10 08 40 AM" src="https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/419840/b0114184-98ce-4d0b-acf0-e17a9d962256">

Select the ammo selector, card is generated:
<img width="816" alt="Screenshot 2024-03-19 at 10 09 07 AM" src="https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/419840/86b9deea-ab42-4f8d-965a-3ca1fa26677b">
<img width="799" alt="Screenshot 2024-03-19 at 10 09 20 AM" src="https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/419840/306241c5-19fc-468d-9152-5a406329f78b">

### Environment - please paste the information from foundry settings tab "support" button:

Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: rqg, 3.4.2
Active Modules: 43
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
GPU: ANGLE (ATI Technologies Inc., AMD Radeon Pro Vega 64 OpenGL Engine, OpenGL 4.1)
Max Texture Size: 16384

Scene: 4512 x 2632 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 9 | Tokens: 4

Actors: 38 | Items: 20 | Journal Entries: 185 | Rollable Tables: 0 |
Playlists: 8 | Compendium Packs: 83 | Chat Messages: 0

**Comment by wake42** [comment]
I can reproduce this bug, adding the case to the next release.

**Comment by wake42** [comment]
Reproduced it - a probable cause is that the event from the select gets counted both for the dropdown select, and for the element under it so that it also responds and initiates an attack (opens the chat message). 
Note: it does not always behave like this for some reason.
