### ISSUE TITLE
Identify Occupational Annual Income Skills Visually (Like RQG)

### ISSUE THREAD

**Issue by claycle** [sun-dragon-cult/fvtt-system-rqg#702]
### Identify Annual Income Skills

It would be convenient to have a simple toggle (checkbox) to indicate which skills possessed by the character could be used for annual income rolls during Sacred Time, as per RQG pg. 63, "Occupational Skills".

### Mimic RAW

The simplest solution seems to be to add a checkbox in the skill definition dialog or a toggle selector in the right-click skill context menu to turn "Income Candidacy" on and off. Skills with the toggle on would, as in RQG, would then be highlighted in some way (Bold Italics, for example, as they are in RQG).

*Even better*...

It would be even better if this toggle would automatically be selected by the system when the character's occupation is set on the background page - with the option above remaining to allow the players to override it based on local table variants.

### Work-Arounds

Currently, a work-around is to modify the name of the skill by adding some identifier that the local table agrees means "this skill is a candidate for income rolls".

### Additional context

The rulebook clearly identifies such income skills in the occupation blocks with bold italics:

<img width="388" alt="image" src="https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/419840/f6a60791-9cb3-4ed0-9331-8928d8e58144">

**Comment by wake42** [comment]
The idea is that the Occupation item should list the occupation skills. That way, when you drag an Occupation item to an actor, one of the things that happen is that the skill list can crosscheck the skills in the skill list and mark them as "income skills". 
In issue #508 there are some (rudimentary) ideas for how Occupation income skills, Cultural bonuses from Homeland & Cult skills could be marked in the skill list, by being present on the Occupation, Homeland & Cult items.

I'm closing this issue as a duplicate, but if you have ideas/opinions on this idea, feel free to continue the discussion in #508!
