### ISSUE TITLE
Incompatibility with Foundry Version 12 Stable Build 324

### ISSUE THREAD

**Issue by The-Axel** [sun-dragon-cult/fvtt-system-rqg#708]
### _What_: Describe the bug

Package Warning for RQG v3.4.3
The system "rqg" is using "gridDistance" which is deprecated in favor of "grid.distance".
The system "rqg" is using "gridUnits" which is deprecated in favor of "grid.units".
The "RuneQuest Glorantha" system's manifest contained the following unknown keys: "type", "release-please-start"

### _How:_ To Reproduce

Go to Foundry Setup
Click on Package Warnings icon.

### Expected behavior

No Package Warnings

**Comment by wake42** [comment]
These (except for the last one) are just warnings that will be removed when I drop support for Foundry v11.
The last one is also a warning - but I'll see if I can get around it. I'm closing this issue for now since it will be solved by other issues.
