### ISSUE TITLE
Cannot roll damage or hit location in Version 12

### ISSUE THREAD

**Issue by The-Axel** [sun-dragon-cult/fvtt-system-rqg#709]
### _What_: Describe the bug

After a successful attack roll, the Damage and Hit Location buttons appear but do not function.
For about 1s they appear clickable when moused over, but after that the outline no longer lights up.

I tested this with only the RQG Wiki module, and only Vasana and Tusker imported from the Compendium.

### _How:_ To Reproduce

1. Open character window.
2. Double click on weapon.
3. Click on attack type in Messages (Cut, Parry, etc.)
4. If roll is Success the Damage and Hit Location buttons appear.
5. Attempt to click them.

### Expected behavior

When clicked on, the Damage and Hit Location buttons generate damage and hit location rolls.

### Environment - please paste the information from foundry settings tab "support" button:
Foundry Virtual Tabletop: Version 12 Stable, 12.324
Game System: rqg, 3.4.3
Active Modules: 1
Performance Mode: 3

OS: Windows 10.0.0 x86 (64-bit)
Client: Not(A:Brand/24.0.0.0
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 (0x00002184) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1200 x 600 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2
Largest Texture: 800 x 400 

Actors: 2 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 56 | Chat Messages: 29

World Scripts:

**Comment by wake42** [comment]
The roll parser in Foundry v12 is more strict, and I seem to have used a sideeffect of the old Roll parser in Foundry v11. Damage rolls with damage bonus was constructed like `(1d8 + 1)1d4` instead of `(1d8+1) + 1d4`
