### ISSUE TITLE
Spirit Magic Spells with Concentration: Active

### ISSUE THREAD

**Issue by The-Axel** [sun-dragon-cult/fvtt-system-rqg#713]
### _What_: Describe the bug

Spirit Magic Spells with Concentration: Active show the wrong value under Concentration on character sheets.

### _How:_ To Reproduce

1. Go to Character sheet
2. Go to Spirit Magic tab.
3. The Concentration column for Spirit Magic spells with Concentration: Active (e.g. Disruption, Ignite) show "RQG.Item.Spell.ConcentrationEnum.

### Expected behavior

The Concentration column for Spirit Magic spells with Concentration: Active (e.g. Disruption, Ignite) shows "Active".

**Comment by wake42** [comment]
The handling of empty translation keys have changed in Foundry 12. Avoid the problem by replacing keys like `""` with `"undefined"`.
