### ISSUE TITLE
Character sheet style making the data unreadable

### ISSUE THREAD

**Issue by Yarblek0** [sun-dragon-cult/fvtt-system-rqg#714]
### _What_: Describe the bug

The UI for the character sheet has mixed up colors and transparency styles which makes it nearly impossible to read the content
That happens both on *Play* & *Edit* modes
The color scheme is different, but it happens at full health, wounded and dead states

See screenshot below

### _How:_ To Reproduce

Versions:

1. Open any Actor sheet (new or existing)
2. See the error
3. Can change tab resize the sheet and style changes
4. Change Character health to see equivalent for wounded or dead states

### Expected behavior

Not exactly sure what the expected experience is with the dynamic state with the health, but I would expect basic "Parchment appearance" most of the item 

### Screenshots

<img width="1877" alt="vtt-css-issue" src="https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/131724627/ca29d10e-eeea-40b1-b1aa-bf93e1ffd99c">

### Environment - please paste the information from foundry settings tab "support" button:

Foundry Virtual Tabletop: Version 12 Stable, 12.325    (did the same thing on 11.315)
Game System: rqg, 3.4.4
Active Modules: 2
Performance Mode: 2

OS: Windows 15.0.0 x86 (64-bit)
Client: Google Chrome/125.0.6422.142
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1800 x 1800 | Grid Size: 50 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 1
Largest Texture: 1200 x 1200 

Actors: 38 | Items: 37 | Journal Entries: 7 | Rollable Tables: 2 |
Playlists: 0 | Compendium Packs: 56 | Chat Messages: 0

World Scripts: 

### Additional context

The problem occurs on a PC on Chrome / Brave / Edge and on a MAC on Chrome / Brave, but is ok on Safari

**Comment by wake42** [comment]
I've opened the actor-sheets both in MacOS and in Windows 11 (I don't know what "windows 15" is) and I can't reproduce that look.

I see you have 2 modules active, apart from the "wiki module" that I guess is one of them, what is the other one? Does disabling it correct the issue?

It's interesting that you see the same issue across multiple computers and web browsers. And even more interesting that it's ok in Safari, that is the browser I would most likely expect something like this from.

Could you please open the dev tools in Chrome (press F12) and see if there are any errors or warnings there.

**Comment by Yarblek0** [comment]
The only modules are mininal one:

- The Forge 1.14.9
- Wiki content for the RQG system 1.3.1

I disabled everything else

I also tried on a freshly created world with RQG to the same effect.

don't know why Foundry brought up Windows 15,  it,s windows 11 home

**Comment by wake42** [comment]
I don't use the Forge myself, but I know it has worked there at least in previous versions. Could you try to install Foundry on your own machine once just to see if it could have something to do with the Forge. Since you see the same behaviour across multiple machines and browsers it seems like it could be a Forge related problem.

**Comment by wake42** [comment]
Is the problem solved, or do you still see this error?

**Comment by Yarblek0** [comment]
I had switched to Firefox in the meantime. but I just checked and everything is fine, both in Chrome & Brave
