### ISSUE TITLE
Can only add one digit at a time to Modifiers box

### ISSUE THREAD

**Issue by The-Axel** [sun-dragon-cult/fvtt-system-rqg#716]
### _What_: Describe the bug

In Chat Messages, when adding a number  to the Other Modifiers box for Skill, Rune, Passion, etc. dice rolls, I can only add one digit (or a minus symbol) at a time. After adding a digit I have to mouse click on the box behind the entered digit or minus symbol to add another. 

### _How:_ To Reproduce

1. Go to Character Sheet.
2. Click on any ability that generates a percentile dice roll. 
3. Click on the Other Modifiers box.
4. Enter a digit. 
5. Attempt to enter a second digit. 

### Expected behavior

Do not need to click on the box a second time.

### Screenshots

![One character in modifier box](https://github.com/sun-dragon-cult/fvtt-system-rqg/assets/149006794/40ed0b52-0301-483f-bfc8-bad61e558037)

### Environment - please paste the information from foundry settings tab "support" button:

Foundry Virtual Tabletop: Version 12 Stable, 12.327
Game System: rqg, 3.4.5
Active Modules: 10
Performance Mode: 2

OS: Unknown
Client: FLC
GPU: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 (0x00002184) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 4176 x 4176 | Grid Size: 72 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 2 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 31
Largest Texture: 4176 x 4176 

Actors: 279 | Items: 832 | Journal Entries: 467 | Rollable Tables: 5 |
Playlists: 8 | Compendium Packs: 81 | Chat Messages: 18146

World Scripts:

**Comment by wake42** [comment]
A known issue in foundry 12 - it will be addressed by a total refactor of how rolls are made, see #695
