### ISSUE TITLE
Support for Gear descriptions

### ISSUE THREAD

**Issue by humburg** [sun-dragon-cult/fvtt-system-rqg#733]
### _Why:_ Is your feature request related to a problem?

Items representing equipment currently have no convenient way to display a description. The only way to this I can see at the moment is to open the edit dialogue for the item.

### _What:_ Describe the solution you'd like

The ability to link a journal entry to the item (similar to how skills, spells, etc. currently work).

### _Options:_ Describe alternatives you've considered

A tooltip showing the item description entered via the edit dialogue could also work but would be less convenient for descriptions that contain links to other journal entries, e.g. spells stored in the item or allied spirits bound in it.

**Comment by wake42** [comment]
I agree that the description should be more easily readable, I have some thoughts about that in this case 
- #248 where a suggestion is to make it behave similar to the back story of passions. 

I think that requiring to create a journalEntry for describing a gear item is not good solution. I agree that consistency is important, but the difference between the description of a skill or spell, and the description of a gear item is that gear is created much more ad hoc, and is much more individual (all swords don't necessarily need the same description for example).

**Comment by humburg** [comment]
Yes, that is a good point. Using the same approach as for Passions seems like a good solution.

**Comment by wake42** [comment]
closing this issue as the following issue refers to the same problem
-  #248
