### ISSUE TITLE
Runes Compendium

### ISSUE THREAD

**Issue by Doubledutchy** [sun-dragon-cult/fvtt-system-rqg#78]
Hi Wake, obviously you have created the main Runes, but are you going to be adding the the other Form and Condition Runes as listed below:-
Form Runes - Plant, Dragonewt, Spirit and Chaos
Condition Runes - Mastery, Magic, Infinity, Luck, Fate and Law
Thanks
Doubledutchy

**Comment by wake42** [comment]
I have a compendium with more runes in the starter-set. But for licensing reasons I've only included the runes on the character sheet in the open system. There is a system setting to name which compendium of runes should be used for rune picking dropdowns etc. 
I can also add that the starter-set rune compendium comes with descriptions of the runes as well. If you open a rune item sheet you can drag a journalEntry to it, and if you then drag that rune to an actor you can click on the rune image to open that journal entry description.
There is support for other form and condition runes as well. And if you drag a Cult that has a rune that the actor does not yet have, that rune is automatically added to the actor (hard to test in the free system, at least without creating a new rune).

**Comment by Doubledutchy** [comment]
I was wondering where a lot of things were. I had had a look through all your workflows for the last 17 to 18 months, and have seen how much work you have put into this, and what you have done, Then I came onto the test system and was thinking that there seems to be a lot of things missing (that I could see from your workflows, that you appear to have done). This is clearly because of licensing issues, which hopefully IKEO will be able to get sorted with Chaosium (with luck)

**Comment by wake42** [comment]
Closing this since they are now included by default.
