### ISSUE TITLE
Rune Points

### ISSUE THREAD

**Issue by Doubledutchy** [sun-dragon-cult/fvtt-system-rqg#79]
Hi Again. When casting a Rune Spell, should the amount of Rune Points the Character has, automatically reduce if the casting was successful. If it should it doesn't appear to be doing so. When Spirit Magic is cast successfully, it does lower the magic points by the relevant amount.

**Comment by wake42** [comment]
That is in the backlog of things to do, but is not implemented yet. The technical reason is that right now I "cheat" a little and use the skill chat card when casting RuneMagic. This also has the effect that it doesn't mark the rune used for casting with an experience check, and wrongly displays a notification that the rune magic spell got the experience check when you succeed with casting the spell.

**Comment by Doubledutchy** [comment]
That's great, as long as you are aware :-)

**Comment by wake42** [comment]
will be adressed in #130, closing this issue.
