### ISSUE TITLE
Investigate if it's possible to drag a complete compendium to actor

### ISSUE THREAD

**Issue by wake42** [sun-dragon-cult/fvtt-system-rqg#86]
This would make it easier to include for example Character Runes and Human hitlocations without having to import them to the word separately first.

**Comment by Moonpile** [comment]
I don't know about dragging a complete compendium to an actor, but I have code for adding a complete compendium to an actor, and that can be executed onCreate.

**Comment by wake42** [comment]
That code  should probably be part of some create wizard. Not all actors should get the same items. A ghost will need much less items than a player character for example.

**Comment by Moonpile** [comment]
Do we want to reject this issue and open another one for "onCreate" dialog?

**Comment by wake42** [comment]
I'll do that! Closing since there now is a case for a create actor wizard #101
